-- Darkmoon Pinball – erster Tisch (geometrischer Prototyp).
-- Kein UI. Collider unabhängig von Assets.

ArcadiaNexus.DMP_TableRegistry.Register({
    id          = "darkmoon_midway",
    displayName = "Darkmoon Midway",
    labelKey    = "dmp_table_midway",
    theme       = "darkmoon",
    version     = 1,
    width       = 280,
    height      = 440,
    gravity     = 820,
    maxSpeed    = 980,
    ballRadius  = 7,
    restitution = 0.72,
    bumperKick  = 260,
    plungerSpeed = 900,
    plungerCharge = 0.55,
    plungerTravel = 22,
    launchVx     = 0,
    ballSaveLaunch = 5,
    extraBallMax   = 1,
    comboWindow    = 2.2,
    ballsPerGame   = 3,
    shooterX       = 253,
    
    launchLane = {
        centerX = 263,
        x = 253,
        yBot = 400,
        yTop = 18,
    },
    -- The ball is guided along the artwork's right-hand launch channel before
    -- entering the playfield through its visible leftward curve.
    
    launchGuide = {
        points = {
            {
                x = 263,
                y = 348,
            },
            {
                x = 263,
                y = 205,
            },
            {
                x = 260,
                y = 187,
            },
            {
                x = 251,
                y = 171,
            },
            {
                x = 237,
                y = 156,
            },
        },
    },
    
    spawn = {
        x = 263,
        y = 348,
    },
    
    drain = {
        -- Open U-shaped drain: all three visible segments are active.
        points = {
            { x = 197,  y = 422.5 },
            { x = 153,  y = 437 },
            { x = 125.5, y = 437 },
            { x = 82.5, y = 421.5 },
        },
        x1 = 197,
        y1 = 422.5,
        x2 = 153,
        y2 = 437,
    },
    outlanes = {
        { id = "out_l", side = "left",  x1 = 14,  y1 = 400, x2 = 82,  y2 = 440 },
        { id = "out_r", side = "right", x1 = 198, y1 = 400, x2 = 246, y2 = 440 },
    },
    
    inlanes = {
        { id = "in_l", side = "left",  x1 = 28,  y1 = 348, x2 = 72,  y2 = 382 },
        { id = "in_r", side = "right", x1 = 208, y1 = 348, x2 = 240, y2 = 382 },
    },
    kickbacks = {
        left  = { vx = 300, vy = -680 },
        right = { vx = -300, vy = -680 },
    },
    kickbackDuration   = 6,
    outlaneSaveDuration = 7,
    nudge = {
        cooldown  = 0.18,
        impulseX  = 210,
        impulseY  = 250,
        tiltLight = 0.12,
        tiltHeavy = 0.28,
        tiltDecay = 0.16,
        warn1     = 0.33,
        warn2     = 0.66,
        warn3     = 0.88,
    },
    
    walls = {
        -- Safety rails keep the ball inside the playable world; the detailed
        -- editor walls below trace the visible table artwork.
        { id = "left",      ax = 14,  ay = 18,  bx = 14,  by = 400 },
        { id = "right",     ax = 273, ay = 18,  bx = 273, by = 400 },
        { id = "top",       ax = 14,  ay = 18,  bx = 273, by = 18 },
        { id = "lane_in",   ax = 253, ay = 175, bx = 253, by = 400 },
        { id = "lane_gate", ax = 253, ay = 18,  bx = 253, by = 175, oneSided = true, nx = -1, ny = 0 },        {
            ax = 253,
            ay = 400,
            bx = 273,
            by = 400,
            id = "lane_bot",
        },
        {
            ax = 95,
            ay = 48,
            bx = 81,
            by = 52.5,
            id = "wall_dev_9",
        },
        {
            ax = 80.5,
            ay = 52.5,
            bx = 72,
            by = 55.5,
            id = "wall_dev_10",
        },
        {
            ax = 72,
            ay = 56,
            bx = 63,
            by = 64,
            id = "wall_dev_11",
        },
        {
            ax = 63,
            ay = 64,
            bx = 50,
            by = 77.5,
            id = "wall_dev_12",
        },
        {
            ax = 50,
            ay = 77.5,
            bx = 43.5,
            by = 89.5,
            id = "wall_dev_13",
        },
        {
            ax = 43.5,
            ay = 89.5,
            bx = 40.5,
            by = 98.5,
            id = "wall_dev_14",
        },
        {
            ax = 40.5,
            ay = 99,
            bx = 47.5,
            by = 108.5,
            id = "wall_dev_15",
        },
        {
            ax = 47.5,
            ay = 108.5,
            bx = 54.5,
            by = 115,
            id = "wall_dev_16",
        },
        {
            ax = 54,
            ay = 115,
            bx = 57.5,
            by = 122.5,
            id = "wall_dev_17",
        },
        {
            ax = 57.5,
            ay = 122.5,
            bx = 56,
            by = 130,
            id = "wall_dev_18",
        },
        {
            ax = 56,
            ay = 130,
            bx = 51,
            by = 142,
            id = "wall_dev_19",
        },
        {
            ax = 51,
            ay = 142,
            bx = 45.5,
            by = 150,
            id = "wall_dev_20",
        },
        {
            ax = 45.5,
            ay = 150,
            bx = 38,
            by = 153.5,
            id = "wall_dev_21",
        },
        {
            ax = 38,
            ay = 153,
            bx = 25,
            by = 234.5,
            id = "wall_dev_22",
        },
        {
            ax = 25,
            ay = 235,
            bx = 25,
            by = 240,
            id = "wall_dev_23",
        },
        {
            ax = 25,
            ay = 240,
            bx = 27,
            by = 244,
            id = "wall_dev_24",
        },
        {
            ax = 27,
            ay = 244,
            bx = 27.5,
            by = 248.5,
            id = "wall_dev_25",
        },
        {
            ax = 27.5,
            ay = 249,
            bx = 28,
            by = 254,
            id = "wall_dev_26",
        },
        {
            ax = 28,
            ay = 254,
            bx = 29,
            by = 257.5,
            id = "wall_dev_27",
        },
        {
            ax = 29,
            ay = 257.5,
            bx = 32,
            by = 261.5,
            id = "wall_dev_28",
        },
        {
            ax = 32,
            ay = 261.5,
            bx = 38,
            by = 267,
            id = "wall_dev_29",
        },
        {
            ax = 38,
            ay = 267,
            bx = 49.5,
            by = 274.5,
            id = "wall_dev_30",
        },
        {
            ax = 49.5,
            ay = 274.5,
            bx = 52.5,
            by = 281,
            id = "wall_dev_31",
        },
        {
            ax = 52.5,
            ay = 281,
            bx = 71,
            by = 330.5,
            id = "wall_dev_32",
        },
        {
            ax = 71,
            ay = 330.5,
            bx = 70,
            by = 334.5,
            id = "wall_dev_33",
        },
        {
            ax = 70,
            ay = 334.5,
            bx = 66.5,
            by = 337.5,
            id = "wall_dev_34",
        },
        {
            ax = 66.5,
            ay = 337.5,
            bx = 62.5,
            by = 337,
            id = "wall_dev_35",
        },
        {
            ax = 62.5,
            ay = 337,
            bx = 29.5,
            by = 319.5,
            id = "wall_dev_36",
        },
        {
            ax = 29.5,
            ay = 319.5,
            bx = 25,
            by = 311.5,
            id = "wall_dev_37",
        },
        {
            ax = 25,
            ay = 311.5,
            bx = 26,
            by = 259.5,
            id = "wall_dev_38",
        },
        {
            ax = 26,
            ay = 259.5,
            bx = 24,
            by = 255,
            id = "wall_dev_39",
        },
        {
            ax = 24,
            ay = 255,
            bx = 18.5,
            by = 300.5,
            id = "wall_dev_40",
        },
        {
            ax = 18.5,
            ay = 300.5,
            bx = 19.5,
            by = 306.5,
            id = "wall_dev_41",
        },
        {
            ax = 19.5,
            ay = 306.5,
            bx = 19,
            by = 311.5,
            id = "wall_dev_42",
        },
        {
            ax = 19,
            ay = 311.5,
            bx = 17,
            by = 325.5,
            id = "wall_dev_43",
        },
        {
            ax = 16.5,
            ay = 325,
            bx = 16.5,
            by = 328,
            id = "wall_dev_45",
        },
        {
            ax = 16.5,
            ay = 328,
            bx = 21.5,
            by = 338,
            id = "wall_dev_46",
        },
        {
            ax = 21.5,
            ay = 338,
            bx = 23.5,
            by = 340,
            id = "wall_dev_47",
        },
        {
            ax = 95,
            ay = 48,
            bx = 106,
            by = 49.5,
            id = "wall_dev_48",
        },
        {
            ax = 106,
            ay = 49.5,
            bx = 115,
            by = 56,
            id = "wall_dev_49",
        },
        {
            ax = 115,
            ay = 56,
            bx = 118,
            by = 62,
            id = "wall_dev_50",
        },
        {
            ax = 118,
            ay = 62,
            bx = 116.5,
            by = 66.5,
            id = "wall_dev_51",
        },
        {
            ax = 116.5,
            ay = 66.5,
            bx = 129,
            by = 73.5,
            id = "wall_dev_52",
        },
        {
            ax = 129,
            ay = 73.5,
            bx = 140,
            by = 88.5,
            id = "wall_dev_53",
        },
        {
            ax = 140,
            ay = 88.5,
            bx = 147.5,
            by = 75,
            id = "wall_dev_54",
        },
        {
            ax = 147.5,
            ay = 75,
            bx = 162.5,
            by = 65.5,
            id = "wall_dev_55",
        },
        {
            ax = 162.5,
            ay = 66,
            bx = 162.5,
            by = 61,
            id = "wall_dev_56",
        },
        {
            ax = 162.5,
            ay = 61,
            bx = 167.5,
            by = 53.5,
            id = "wall_dev_57",
        },
        {
            ax = 167.5,
            ay = 53.5,
            bx = 187,
            by = 52,
            id = "wall_dev_58",
        },
        {
            ax = 187,
            ay = 52,
            bx = 199,
            by = 57,
            id = "wall_dev_59",
        },
        {
            ax = 199,
            ay = 57,
            bx = 210.5,
            by = 61.5,
            id = "wall_dev_60",
        },
        {
            ax = 210.5,
            ay = 61.5,
            bx = 225.5,
            by = 75.5,
            id = "wall_dev_61",
        },
        {
            ax = 225.5,
            ay = 75.5,
            bx = 234,
            by = 84.5,
            id = "wall_dev_62",
        },
        {
            ax = 234,
            ay = 84.5,
            bx = 237,
            by = 90,
            id = "wall_dev_63",
        },
        {
            ax = 237,
            ay = 90,
            bx = 237.5,
            by = 97.5,
            id = "wall_dev_64",
        },
        {
            ax = 237.5,
            ay = 97.5,
            bx = 234.5,
            by = 104,
            id = "wall_dev_65",
        },
        {
            ax = 234.5,
            ay = 104,
            bx = 223,
            by = 115,
            id = "wall_dev_66",
        },
        {
            ax = 223,
            ay = 115,
            bx = 221,
            by = 127,
            id = "wall_dev_67",
        },
        {
            ax = 221,
            ay = 127,
            bx = 225.5,
            by = 139,
            id = "wall_dev_68",
        },
        {
            ax = 225.5,
            ay = 139,
            bx = 234,
            by = 151,
            id = "wall_dev_69",
        },
        {
            ax = 234,
            ay = 151,
            bx = 242,
            by = 153.5,
            id = "wall_dev_70",
        },
        {
            ax = 241.5,
            ay = 153,
            bx = 242.5,
            by = 156.5,
            id = "wall_dev_71",
        },
        {
            ax = 246,
            ay = 180.5,
            bx = 252,
            by = 233.5,
            id = "wall_dev_72",
        },
        {
            ax = 252,
            ay = 233.5,
            bx = 252.5,
            by = 243,
            id = "wall_dev_73",
        },
        {
            ax = 252.5,
            ay = 243,
            bx = 252,
            by = 254,
            id = "wall_dev_74",
        },
        {
            ax = 251.5,
            ay = 253,
            bx = 249,
            by = 260,
            id = "wall_dev_75",
        },
        {
            ax = 249,
            ay = 260,
            bx = 241,
            by = 266.5,
            id = "wall_dev_76",
        },
        {
            ax = 209.5,
            ay = 330.5,
            bx = 210,
            by = 335.5,
            id = "wall_dev_80",
        },
        {
            ax = 210,
            ay = 335.5,
            bx = 213.5,
            by = 338,
            id = "wall_dev_81",
        },
        {
            ax = 213.5,
            ay = 338,
            bx = 221,
            by = 335,
            id = "wall_dev_82",
        },
        {
            ax = 221,
            ay = 335,
            bx = 252.5,
            by = 320,
            id = "wall_dev_83",
        },
        {
            ax = 240.5,
            ay = 266,
            bx = 229,
            by = 275.5,
            id = "wall_dev_87",
        },
        {
            ax = 229,
            ay = 275.5,
            bx = 209.5,
            by = 330.5,
            id = "wall_dev_88",
        },
        {
            ax = 242,
            ay = 156.5,
            bx = 246,
            by = 181,
            id = "wall_dev_89",
        },
        { id = "wall_dev_90", ax = 253, ay = 319,     bx = 257,   by = 314.5 },
        { id = "wall_dev_91", ax = 257, ay = 314.5,   bx = 257,   by = 339 },
        { id = "wall_dev_92", ax = 257, ay = 339,     bx = 240.5, by = 353.5 },
        { id = "wall_dev_93", ax = 241, ay = 352.5,   bx = 235.5, by = 340.5 },
        { id = "wall_dev_94", ax = 200, ay = 395,     bx = 201.5, by = 392 },
        { id = "wall_dev_95", ax = 196.5, ay = 405.5, bx = 196.5, by = 421 },
        { id = "wall_dev_96", ax = 83, ay = 419.5,    bx = 83,    by = 406 },
        { id = "wall_dev_97", ax = 77.5, ay = 392,    bx = 79,    by = 396.5 },
    },
    
    slingshots = {
        {
            ax = 24,
            ay = 340,
            bx = 78,
            by = 392,
            id = "sling_l",
            kick = 180,
        },
        {
            ax = 202,
            ay = 392,
            bx = 236,
            by = 340,
            id = "sling_r",
            kick = 180,
        },
    },
    
    kickers = {
    },
    
    bumpers = {
        {
            id = "bumper_c",
            kick = 260,
            r = 12.021,
            score = 100,
            x = 140,
            y = 232,
        },
        {
            id = "bumper_l",
            kick = 220,
            r = 7.211,
            score = 75,
            x = 89,
            y = 192,
        },
        {
            id = "bumper_r",
            kick = 220,
            r = 7.632,
            score = 75,
            x = 190.5,
            y = 191,
        },
    },
    bumperBank = { missionId = "bumper_overdrive" },
    
    posts = {
    },
    
    ramps = {
        { id = "ramp_l", side = "left",  x1 = 28,  y1 = 48, x2 = 72,  y2 = 92 },
        { id = "ramp_r", side = "right", x1 = 174, y1 = 48, x2 = 218, y2 = 92 },
    },
    rampModule = { missionId = "ramp_run" },
    
    targets = {
        {
            id = "t1",
            order = 1,
            r = 8,
            x = 107,
            y = 141,
        },
        {
            id = "t2",
            order = 2,
            r = 8,
            x = 140,
            y = 124,
        },
        {
            id = "t3",
            order = 3,
            r = 8,
            x = 173.5,
            y = 140.5,
        },
    },
    targetBank = { missionId = "target_hunt" },
    
    lock = {
        id = "lock_dev",
        x1 = 126.5,
        x2 = 153,
        y1 = 186,
        y2 = 201.5,
    },
    
    jackpot = {
        id = "jackpot_dev",
        x1 = 132,
        x2 = 147.5,
        y1 = 80.5,
        y2 = 91,
    },
    lockModule = { missionId = "arcane_lock", need = 3 },
    magnet = { x = 140, y = 228 },
    mbSpawns = {
        { x = 96, y = 210, vx = -80, vy = 50 },
        { x = 184, y = 210, vx = 80, vy = 50 },
        { x = 140, y = 150, vx = 0, vy = 80 },
    },
    multiballDefinitions = {
        balls = 3,
        save = 1,
        jackpotEvery = 3,
    },
    missionDefinitions = {
        { id = "bumper_overdrive", need = 14, time = 24, score = 2500, reward = "frenzy" },
        { id = "ramp_run",         need = 3,  time = 26, score = 4000, reward = "extra_ball" },
        { id = "target_hunt",      need = 3,  time = 24, score = 2000, reward = "shield" },
        { id = "arcane_lock",      need = 3,  time = 24, score = 1500, reward = "multiball" },
    },
    missionTime = {
        bumper_overdrive = 24,
        ramp_run = 26,
        target_hunt = 24,
        arcane_lock = 24,
    },
    scoringRules = {
        ramp = 150,
        target = 120,
        lock = 200,
        extraBallBank = 2500,
    },
    frenzyTime = 5,
    frenzyMul = 2,
    magnetTime = 2.5,
    mbSave = 1,
    lockDark = 18,
    jackpotScore = 2500,
    superJackpotScore = 10000,
    assets = { playfield = "midway_field", ball = "ball_base" },
    audioProfile = { id = "midway" },
    fxProfile = { id = "midway" },
    
    flippers = {
        {
            activeAngle = -0.58,
            id = "left",
            length = 46,
            px = 86,
            py = 396,
            radius = 5,
            restAngle = 0.52,
            restitution = 0.35,
            returnSpeed = 14,
            swingSpeed = 18,
        },
        {
            activeAngle = 3.722,
            id = "right",
            length = 46,
            px = 194,
            py = 396,
            radius = 5,
            restAngle = 2.622,
            restitution = 0.35,
            returnSpeed = 14,
            swingSpeed = 18,
        },
        {
            activeAngle = 0.118,
            id = "left_dev",
            length = 46,
            px = 51,
            py = 278,
            radius = 5,
            restAngle = 1.218,
            restitution = 0.35,
            returnSpeed = 14,
            swingSpeed = 18,
        },
        {
            activeAngle = 3.023,
            id = "right_dev",
            length = 46,
            px = 227,
            py = 282.5,
            radius = 5,
            restAngle = 1.923,
            restitution = 0.35,
            returnSpeed = 14,
            swingSpeed = 18,
        },
    },
})
