ArcadiaNexus.RegisterLocale("BACKGAMMON", "deDE", {
    title = "BACKGAMMON", subtitle = "Gold, Holz und ein guter Wurf.",
    btn_start = "Spiel starten", btn_exit = "Beenden", btn_menu = "Beenden", btn_retry = "Neues Spiel",
    btn_new_game = "Neues Spiel", btn_continue = "Fortfahren",
    btn_roll = "Würfeln", btn_confirm = "Zug bestätigen", btn_pass = "Kein Zug · passen",
    btn_undo = "Zurück", btn_save = "Speichern & Ende", btn_back = "Zurück",
    btn_sync = "Abgleichen", network_wait = "Keine Antwort. Abgleichen oder den Zug erneut bestätigen.",
    sending = "Warte auf die Bestätigung des Hosts …",
    player_1 = "Elfenbein", player_2 = "Obsidian",
    difficulty_easy = "Lehrling", difficulty_normal = "Herausforderer", difficulty_hard = "Meister",
    pip = "%s · %d Pips", off = "AUS", bar = "BAR", turn = "Zug %d · %s",
    opening = "Eröffnungswurf: je ein Würfel pro Farbe. Der höhere beginnt.",
    tie = "Gleichstand im Eröffnungswurf. Noch einmal würfeln.",
    roll = "%s ist am Zug. Würfeln!", select = "Stein wählen, dann ein markiertes Ziel anklicken.",
    confirm = "Zug vollständig. Bestätigen oder zurücknehmen.",
    blocked = "Kein legaler Zug. Bestätige das Passen.", waiting = "Warte auf %s …",
    choose_die = "Auswürfeln mit: ", dice_hint = "Würfel anklicken, um die Augenzahl für den nächsten Schritt zu wählen.",
    victory = "%s gewinnt!", win_1 = "Einfacher Sieg", win_2 = "Gammon · 2 Punkte", win_3 = "Backgammon · 3 Punkte",
    mp_hint = "Online spielen: im Hub-Tab Mehrspieler eine Backgammon-Partie öffnen.",
    nomp = "Multiplayer ist deaktiviert. Gegen die KI kannst du weiter spielen.",
    bad_save = "Dieser Spielstand kann nicht geladen werden.", aborted = "Die Mehrspieler-Partie wurde beendet.",
    need_ready = "Zwei Spieler müssen bereit sein.", saved_info = "Zug %d · %s", multiplayer = "Mehrspieler",
    box_sounds = "Sound", sound_enabled = "Sound aktivieren", box_theme = "Spielbrett",
    theme_walnut = "Walnuss & Gold", theme_midnight = "Mitternacht", box_guide = "Spielanleitung",
    btn_reset = "Zurücksetzen",
    guide_goal = "Bringe alle 15 Steine ins eigene Heimfeld und trage sie zuerst ab. Elfenbein läuft von 24 nach 1, Obsidian von 1 nach 24. Online liegt dein Heimfeld unten rechts.",
    guide_moves = "Klicke einen Stein und danach ein markiertes Ziel. Jeder Schritt nutzt einen Würfel. Du musst möglichst viele Würfel nutzen; geht nur einer, gilt die höhere Zahl, falls spielbar. Ein Pasch zählt viermal.",
    guide_bar = "Ein einzelner gegnerischer Stein wird geschlagen und landet auf der Bar. Eigene Steine auf der Bar müssen zuerst eingesetzt werden. Zwei gegnerische Steine sperren einen Punkt.",
    guide_off = "Abtragen geht erst, wenn alle eigenen Steine im Heimfeld sind. Eine zu hohe Zahl darf nur den am weitesten entfernten Stein abtragen. Wähle bei Bedarf vorher den Würfel.",
    guide_confirm = "Vor dem Bestätigen kannst du Schritte zurücknehmen. Ohne Zugmöglichkeit musst du passen. Lokale Partien werden nach jedem Wurf und bestätigten Zug gespeichert; offene Schritte werden beim Fortsetzen zurückgesetzt.",
    guide_mp = "KI: Lehrling zieht zufällig, Herausforderer bewertet direkte Züge, Meister achtet zusätzlich auf Sicherheit, Heimfeld und Primen. Mehrspieler: Host und Gast klicken Bereit, dann startet der Host. Der Host würfelt und prüft alle Züge. Einzelpartien ohne Verdopplungswürfel; Gammon und Backgammon werden erkannt.",
})
ArcadiaNexus.RegisterLocale("BACKGAMMON", "enUS", {
    title = "BACKGAMMON", subtitle = "Walnut, gold, and a little luck.",
    btn_start = "Start game", btn_exit = "Exit", btn_menu = "Exit", btn_retry = "New game",
    btn_new_game = "New game", btn_continue = "Continue",
    btn_roll = "Roll dice", btn_confirm = "Confirm turn", btn_pass = "No move · pass",
    btn_undo = "Undo", btn_save = "Save & exit", btn_back = "Back",
    btn_sync = "Resync", network_wait = "No reply. Resync or confirm the turn again.",
    sending = "Waiting for the host to confirm …",
    player_1 = "Ivory", player_2 = "Obsidian",
    difficulty_easy = "Apprentice", difficulty_normal = "Challenger", difficulty_hard = "Master",
    pip = "%s · %d pips", off = "OFF", bar = "BAR", turn = "Turn %d · %s",
    opening = "Opening roll: one die per colour. The higher die starts.",
    tie = "Opening tie. Roll again.", roll = "%s to play. Roll the dice!",
    select = "Select a checker, then click a highlighted destination.",
    confirm = "Turn complete. Confirm or undo.", blocked = "No legal move. Confirm to pass.",
    waiting = "Waiting for %s …", choose_die = "Bear off with: ",
    dice_hint = "Click a die to choose its value for your next move.",
    victory = "%s wins!", win_1 = "Single game", win_2 = "Gammon · 2 points", win_3 = "Backgammon · 3 points",
    mp_hint = "Play online: open a Backgammon session in the Multiplayer hub tab.",
    nomp = "Multiplayer is disabled. You can still play against the AI.",
    bad_save = "This saved game cannot be loaded.", aborted = "The multiplayer game has ended.",
    need_ready = "Two players must be ready.", saved_info = "Turn %d · %s", multiplayer = "Multiplayer",
    box_sounds = "Sound", sound_enabled = "Enable sound", box_theme = "Board",
    theme_walnut = "Walnut & gold", theme_midnight = "Midnight", box_guide = "How to play", btn_reset = "Reset",
    guide_goal = "Move all 15 checkers into your home board and bear them off first. Ivory moves from 24 to 1; Obsidian moves from 1 to 24. Online, your home board is at the bottom right.",
    guide_moves = "Click a checker and a highlighted destination. Each step uses one die. Use as many dice as possible; if only one can be played, use the higher number when possible. Doubles give four moves.",
    guide_bar = "A single opposing checker is hit and sent to the bar. Checkers on your bar must enter before you move other checkers. Two opposing checkers block a point.",
    guide_off = "Bear off only when all your checkers are home. An oversized die can only remove your furthest checker. Select a die first when the choice matters.",
    guide_confirm = "Undo steps before confirming. Pass when no move exists. Local games save after every roll and confirmed turn; unfinished steps reset on resume.",
    guide_mp = "AI: Apprentice selects legal moves at random, Challenger evaluates direct moves, and Master also prioritizes safety, home-board strength, and primes. Multiplayer: both players click Ready, then the host starts. The host rolls and validates all turns. Single games without a doubling cube; gammons and backgammons are scored.",
})
