ArcadiaNexus.RegisterLocale("SI7", "deDE", {
    btn_start       = "Spiel starten",
    btn_exit        = "Beenden",
    btn_ready       = "Bereit",
    btn_match       = "Runde starten",
    btn_clue        = "Hinweis",
    btn_pass        = "Passen",
    btn_retry       = "Nochmal",
    btn_menu        = "Beenden",

    mode_hotseat    = "Hotseat",
    mode_host       = "Host (MP)",
    mode_join       = "Beitreten",

    role_1          = "Spion Horde",
    role_2          = "Agent Horde",
    role_3          = "Spion Allianz",
    role_4          = "Agent Allianz",
    role_neutral_1  = "Spion Rot",
    role_neutral_2  = "Agent Rot",
    role_neutral_3  = "Spion Blau",
    role_neutral_4  = "Agent Blau",

    team_R          = "Horde",
    team_B          = "Allianz",
    team_neutral_R  = "Team Rot",
    team_neutral_B  = "Team Blau",

    hud_turn        = "Zug: %s",
    hud_phase_C     = "Hinweis legen",
    hud_phase_G     = "Raten",
    hud_phase_O     = "Ende",
    hud_clue        = "Hinweis: %s  (%s)",
    hud_left        = "Horde %d · Allianz %d",
    hud_left_neutral = "Rot %d · Blau %d",
    hud_lobby       = "Lobby · warte auf 4 Spieler und Bereit",
    hud_lobby_host  = "Vier Spieler: zwei Paare à 2. Beim Start würfelt das Spiel Horde/Allianz und Spion/Agent — jeder Client eine Rolle. Zwei Spieler gehen auch: jeder spielt ein ganzes Paar.",
    hud_lobby_guest = "Bereit klicken. Der Host teilt die Paare; bei vieren spielt jeder eine Rolle.",
    hud_lobby_set   = "Wortset des Hosts: %s",
    hud_lobby_duo   = "Zwei Spieler: jedes Paar spielt Spion und Agent auf dem eigenen Client. Rollenleiste zum Umschalten.",
    hud_lobby_quad  = "Vier Spieler — Klassik 2v2. Paare prüfen, alle bereit, dann starten. Jeder spielt nur die eigene Rolle.",
    hud_lobby_quad_guest = "Vier Spieler: dein Paar siehst du an den Markierungen. Bereit klicken und auf den Host warten.",
    hud_groups      = "Paar %s",
    hud_groups_need = "Jedes Paar braucht genau 2 Spieler.",
    hud_start_fail  = "Start fehlgeschlagen — 2 oder 4 Spieler, alle müssen bereit sein.",
    btn_pair_a      = "Paar 1",
    btn_pair_b      = "Paar 2",
    hud_ready_yes   = "bereit",
    hud_ready_no    = "wartet",
    hud_wait        = "Warten auf Host…",
    hud_nomp        = "Multiplayer-Modul nicht geladen.",
    hud_joinhint    = "Partei oder Name-Realm eingeben",
    hud_view_clue   = "Ansicht: %s — Hinweis senden",
    hud_view_guess  = "Ansicht: %s — Karte wählen oder passen",
    hud_view_wait   = "Ansicht: %s — nicht am Zug",
    clue_empty      = "Bitte einen Hinweis eingeben.",
    clue_long       = "Ein Hinweis darf höchstens 16 Zeichen haben.",
    clue_chars      = "Ein Hinweis darf nur Buchstaben enthalten.",
    clue_board      = "Der Hinweis steht bereits auf dem Brett.",
    hud_history_clue = "%s gab den Hinweis %s (%d)",
    hud_history_guess = "%s deckte %s auf",
    hud_history_pass = "%s passt.",

    go_win_R        = "Die Horde gewinnt!",
    go_win_B        = "Die Allianz gewinnt!",
    go_cleared_R    = "Alle Horde-Agenten wurden identifiziert.",
    go_cleared_B    = "Alle Allianz-Agenten wurden identifiziert.",
    go_assassin_R   = "Ein Horde-Agent hat den Assassinen aufgedeckt — die Allianz gewinnt.",
    go_assassin_B   = "Ein Allianz-Agent hat den Assassinen aufgedeckt — die Horde gewinnt.",
    go_win_neutral_R = "Team Rot gewinnt!",
    go_win_neutral_B = "Team Blau gewinnt!",
    go_cleared_neutral_R = "Alle roten Agenten wurden identifiziert.",
    go_cleared_neutral_B = "Alle blauen Agenten wurden identifiziert.",
    go_assassin_neutral_R = "Ein roter Agent hat den Assassinen aufgedeckt — Team Blau gewinnt.",
    go_assassin_neutral_B = "Ein blauer Agent hat den Assassinen aufgedeckt — Team Rot gewinnt.",
    go_hotseat      = "Hotseat — kein XP (nur Mehrspieler zählt).",
    go_mp_win       = "Euer Team hat die Lage unter Kontrolle.",
    go_mp_loss      = "Die Gegenseite war schneller.",

    box_sounds      = "Sound",
    box_guide       = "Anleitung",
    box_wordset     = "Wortset",
    wordset_label   = "Kartenthema",
    wordset_tooltip = "Bestimmt das Thema neuer eigener Runden. Im Mehrspieler gilt immer die Auswahl des Hosts.",
    wordset_azeroth = "Azeroth",
    wordset_azeroth_tooltip = "Orte, Figuren und Begriffe aus World of Warcraft.",
    wordset_everyday = "Alltag",
    wordset_everyday_tooltip = "Allgemeine Begriffe aus Haushalt, Essen, Stadt und Beruf.",
    wordset_nature  = "Natur",
    wordset_nature_tooltip = "Landschaften, Pflanzen und Naturphaenomene aus aller Welt.",
    wordset_travel  = "Welt & Reisen",
    wordset_travel_tooltip = "Reiseziele, Wege und Begriffe rund ums Unterwegssein.",
    clue_placeholder = "Hinweis eingeben…",
    box_accessibility = "Barrierefreiheit",
    colorblind_symbols = "Farben mit Kartenmarkern ergänzen",
    sound_enabled   = "Soundeffekte",
    btn_reset       = "Reset",

    guide_goal      = "|cffffff00Ziel:|r Zwei Teams (Horde / Allianz) finden ihre Agenten auf dem Raster. Spione kennen die Farben, Agenten nur die Wörter.",
    guide_hotseat   = "|cffffff00Hotseat:|r Alle vier Rollen an einem Rechner. Wechsle die Ansicht, damit niemand die Key-Karte der anderen Seite sieht.",
    guide_clue      = "|cffffff00Hinweis:|r Der Spion sendet EIN Wort (kein Brettwort) plus Zahl. 0 = unbegrenzt raten, bis Pass oder Fehlgriff.",
    guide_guess     = "|cffffff00Raten:|r Agenten decken Karten auf. Eigene Farbe: weiter. Neutral oder Gegner: Zugende. Die eine schwarze Karte ist der Assassine — wer sie aufdeckt, verliert sofort, das andere Team gewinnt. Sieg nur, wenn alle eigenen Agenten (Horde 9 / Allianz 8) gefunden sind.",
    guide_mp        = "|cffffff00Mehrspieler:|r Klassik sind vier Spieler (2v2), alle bereit. Jeder spielt eine Rolle. Zwei Spieler gehen als Fallback: jeder Client ein ganzes Paar (Rollenleiste). Der Host teilt Paar 1/2. Beim Start würfelt das Spiel Horde (9 Agenten, beginnt) / Allianz und Spion/Agent. XP nur in echten MP-Runden.",
})

ArcadiaNexus.RegisterLocale("SI7", "enUS", {
    btn_start       = "Start game",
    btn_exit        = "Exit",
    btn_ready       = "Ready",
    btn_match       = "Start round",
    btn_clue        = "Clue",
    btn_pass        = "Pass",
    btn_retry       = "Again",
    btn_menu        = "Exit",

    mode_hotseat    = "Hotseat",
    mode_host       = "Host (MP)",
    mode_join       = "Join",

    role_1          = "Horde spymaster",
    role_2          = "Horde operative",
    role_3          = "Alliance spymaster",
    role_4          = "Alliance operative",
    role_neutral_1  = "Red spymaster",
    role_neutral_2  = "Red operative",
    role_neutral_3  = "Blue spymaster",
    role_neutral_4  = "Blue operative",

    team_R          = "Horde",
    team_B          = "Alliance",
    team_neutral_R  = "Red team",
    team_neutral_B  = "Blue team",

    hud_turn        = "Turn: %s",
    hud_phase_C     = "Give a clue",
    hud_phase_G     = "Guess",
    hud_phase_O     = "Over",
    hud_clue        = "Clue: %s  (%s)",
    hud_left        = "Horde %d · Alliance %d",
    hud_left_neutral = "Red %d · Blue %d",
    hud_lobby       = "Lobby · waiting for 4 players and ready",
    hud_lobby_host  = "Four players: two pairs of 2. At start the game rolls Horde/Alliance and spy/operative — one role per client. Two players also work: each client plays a full pair.",
    hud_lobby_guest = "Click ready. The host sets the pairs; with four, each player has one role.",
    hud_lobby_set   = "Host word set: %s",
    hud_lobby_duo   = "Two players: each pair plays spy and operative on their client. Use the role bar to switch.",
    hud_lobby_quad  = "Four players — classic 2v2. Check pairs, everyone ready, then start. Each player has one role.",
    hud_lobby_quad_guest = "Four players: your pair is marked. Click ready and wait for the host.",
    hud_groups      = "Pair %s",
    hud_groups_need = "Each pair needs exactly 2 players.",
    hud_start_fail  = "Start failed — 2 or 4 players, everyone must be ready.",
    btn_pair_a      = "Pair 1",
    btn_pair_b      = "Pair 2",
    hud_ready_yes   = "ready",
    hud_ready_no    = "waiting",
    hud_wait        = "Waiting for host…",
    hud_nomp        = "Multiplayer module not loaded.",
    hud_joinhint    = "Party or enter Name-Realm",
    hud_view_clue   = "View: %s — send a clue",
    hud_view_guess  = "View: %s — pick a card or pass",
    hud_view_wait   = "View: %s — not your turn",
    clue_empty      = "Enter a clue first.",
    clue_long       = "A clue may contain at most 16 characters.",
    clue_chars      = "A clue may contain letters only.",
    clue_board      = "That clue is already on the board.",
    hud_history_clue = "%s gave the clue %s (%d)",
    hud_history_guess = "%s revealed %s",
    hud_history_pass = "%s passes.",

    go_win_R        = "The Horde wins!",
    go_win_B        = "The Alliance wins!",
    go_cleared_R    = "All Horde agents were identified.",
    go_cleared_B    = "All Alliance agents were identified.",
    go_assassin_R   = "A Horde operative revealed the assassin — the Alliance wins.",
    go_assassin_B   = "An Alliance operative revealed the assassin — the Horde wins.",
    go_win_neutral_R = "The red team wins!",
    go_win_neutral_B = "The blue team wins!",
    go_cleared_neutral_R = "All red operatives were identified.",
    go_cleared_neutral_B = "All blue operatives were identified.",
    go_assassin_neutral_R = "A red operative revealed the assassin — the blue team wins.",
    go_assassin_neutral_B = "A blue operative revealed the assassin — the red team wins.",
    go_hotseat      = "Hotseat — no XP (multiplayer only).",
    go_mp_win       = "Your team controlled the field.",
    go_mp_loss      = "The other side was faster.",

    box_sounds      = "Sound",
    box_guide       = "How to play",
    box_wordset     = "Word set",
    wordset_label   = "Card theme",
    wordset_tooltip = "Sets the theme for new games you start. In multiplayer, the host's selection always applies.",
    wordset_azeroth = "Azeroth",
    wordset_azeroth_tooltip = "Places, characters, and terms from World of Warcraft.",
    wordset_everyday = "Everyday life",
    wordset_everyday_tooltip = "General words from home, food, city life, and jobs.",
    wordset_nature  = "Nature",
    wordset_nature_tooltip = "Landscapes, plants, and natural phenomena from around the world.",
    wordset_travel  = "World & travel",
    wordset_travel_tooltip = "Destinations, routes, and words about exploring the world.",
    clue_placeholder = "Enter clue…",
    box_accessibility = "Accessibility",
    colorblind_symbols = "Add card markers for colors",
    sound_enabled   = "Sound effects",
    btn_reset       = "Reset",

    guide_goal      = "|cffffff00Goal:|r Two teams (Horde / Alliance) find their agents. Spymasters see colors; operatives see words only.",
    guide_hotseat   = "|cffffff00Hotseat:|r All four roles on one client. Switch the view so nobody sees the other key card.",
    guide_clue      = "|cffffff00Clue:|r The spymaster sends ONE word (not on the board) plus a number. 0 = unlimited guesses until pass or miss.",
    guide_guess     = "|cffffff00Guess:|r Operatives reveal cards. Own color: continue. Neutral or enemy: turn ends. The single black card is the assassin — revealing it is an instant loss, the other team wins. You win only by finding all of your agents (Horde 9 / Alliance 8).",
    guide_mp        = "|cffffff00Multiplayer:|r Classic is four players (2v2), all ready. Each player has one role. Two players is the fallback: each client plays a full pair (role bar). The host sets pair 1/2. At start the game rolls Horde (9 agents, goes first) / Alliance and spy vs operative. XP only in real MP rounds.",
})
