--[[
    Azeroth Intelligence — SI:7 word-set registry.
    Board IDs are indices inside the selected set. The host sends the set
    code once in START; later packets contain only compact card IDs.
]]

ArcadiaNexus = ArcadiaNexus or {}
ArcadiaNexus.SI7_WordSets = {}
local Sets = ArcadiaNexus.SI7_WordSets

local function ParsePairs(source)
    local words = {}
    for row in string.gmatch(source or "", "[^|]+") do
        local de, en = row:match("^(.-)~(.-)$")
        if de and en and de ~= "" and en ~= "" then
            words[#words + 1] = { deDE = de, enUS = en }
        end
    end
    return words
end

local function MakeCompounds(prefixes, suffixes)
    local words = {}
    for _, prefix in ipairs(prefixes) do
        for _, suffix in ipairs(suffixes) do
            words[#words + 1] = {
                deDE = prefix.de .. suffix.de,
                enUS = prefix.en .. " " .. suffix.en,
            }
        end
    end
    return words
end

Sets.order = { "AZEROTH", "EVERYDAY", "NATURE", "TRAVEL" }
Sets.data = {
    AZEROTH = { code = "A", localized = true, words = ArcadiaNexus.SI7_Words },
    EVERYDAY = {
        code = "E", neutral = true,
        words = ParsePairs([[TISCH~TABLE|STUHL~CHAIR|FENSTER~WINDOW|TUER~DOOR|LAMPE~LAMP|TEPPICH~RUG|SOFA~SOFA|BETT~BED|KISSEN~PILLOW|DECKE~BLANKET|SCHRANK~CUPBOARD|REGAL~SHELF|SPIEGEL~MIRROR|UHR~CLOCK|KERZE~CANDLE|VORHANG~CURTAIN|VASE~VASE|BILDERAHMEN~PICTURE FRAME|SCHLUESSEL~KEY|BRIEFKASTEN~MAILBOX|TELLER~PLATE|TASSE~CUP|GLAS~GLASS|GABEL~FORK|MESSER~KNIFE|LOEFFEL~SPOON|TOPF~POT|PFANNE~PAN|OFEN~OVEN|HERD~STOVE|KUEHLSCHRANK~FRIDGE|GEFRIERSCHRANK~FREEZER|TOASTER~TOASTER|WASSERKOCHER~KETTLE|MIXER~BLENDER|SCHNEIDEBRETT~CHOPPING BOARD|SERVIETTE~NAPKIN|FLASCHE~BOTTLE|DOSE~TIN|REIBE~GRATER|APFEL~APPLE|BANANE~BANANA|BIRNE~PEAR|ERDBEERE~STRAWBERRY|KIRSCHE~CHERRY|ZITRONE~LEMON|ORANGE~ORANGE|TRAUBE~GRAPE|MELONE~MELON|KAROTTE~CARROT|KARTOFFEL~POTATO|TOMATE~TOMATO|GURKE~CUCUMBER|ZWIEBEL~ONION|PAPRIKA~PEPPER|PILZ~MUSHROOM|BROT~BREAD|KAESE~CHEESE|BUTTER~BUTTER|HONIG~HONEY|NUDELN~PASTA|REIS~RICE|SUPPE~SOUP|SALAT~SALAD|PIZZA~PIZZA|KUCHEN~CAKE|KEKS~COOKIE|EIS~ICE CREAM|KAFFEE~COFFEE|TEE~TEA|SAFT~JUICE|HEMD~SHIRT|HOSE~TROUSERS|JACKE~JACKET|MANTEL~COAT|KLEID~DRESS|ROCK~SKIRT|SCHUH~SHOE|STIEFEL~BOOT|SOCKE~SOCK|HUT~HAT|MUETZE~CAP|SCHAL~SCARF|HANDSCHUH~GLOVE|GUERTEL~BELT|TASCHE~BAG|RUCKSACK~BACKPACK|SCHIRM~UMBRELLA|BRILLE~GLASSES|ZAHNBUERSTE~TOOTHBRUSH|SEIFE~SOAP|HANDTUCH~TOWEL|KAMM~COMB|BUERSTE~BRUSH|RASIERER~RAZOR|SHAMPOO~SHAMPOO|CREME~CREAM|PFLASTER~BANDAGE|FAHRRAD~BICYCLE|AUTO~CAR|BUS~BUS|ZUG~TRAIN|TAXI~TAXI|MOTORRAD~MOTORCYCLE|ROLLER~SCOOTER|TRAKTOR~TRACTOR|BOOT~BOAT|SCHIFF~SHIP|FLUGZEUG~AIRPLANE|HELIKOPTER~HELICOPTER|RAKETE~ROCKET|TANKSTELLE~PETROL STATION|AMPEL~TRAFFIC LIGHT|KREUZUNG~CROSSROADS|BRUECKE~BRIDGE|TUNNEL~TUNNEL|BAHNHOF~STATION|FLUGHAFEN~AIRPORT|KARTE~MAP|KOMPASS~COMPASS|HANDY~PHONE|COMPUTER~COMPUTER|TASTATUR~KEYBOARD|MAUS~MOUSE|BILDSCHIRM~SCREEN|KOPFHOERER~HEADPHONES|KAMERA~CAMERA|FERNBEDIENUNG~REMOTE CONTROL|LADEKABEL~CHARGING CABLE|BATTERIE~BATTERY|DRUCKER~PRINTER|LAUTSPRECHER~SPEAKER|MIKROFON~MICROPHONE|TASCHENLAMPE~FLASHLIGHT|WECKER~ALARM CLOCK|RADIO~RADIO|BUCH~BOOK|HEFT~NOTEBOOK|STIFT~PEN|BLEISTIFT~PENCIL|RADIERGUMMI~ERASER|LINEAL~RULER|SCHERE~SCISSORS|KLEBER~GLUE|PAPIER~PAPER|ORDNER~FOLDER|RANZEN~SCHOOLBAG|TAFEL~BLACKBOARD|KREIDE~CHALK|LEHRER~TEACHER|ARZT~DOCTOR|PFLEGER~NURSE|KOCH~COOK|BAUER~FARMER|FAHRER~DRIVER|PILOT~PILOT|POLIZIST~POLICE OFFICER|FEUERWEHR~FIREFIGHTER|MALER~PAINTER|MUSIKER~MUSICIAN|BAECKER~BAKER|GAERTNER~GARDENER|MARKT~MARKET|LADEN~SHOP|APOTHEKE~PHARMACY|BIBLIOTHEK~LIBRARY|SCHULE~SCHOOL|KRANKENHAUS~HOSPITAL|PARK~PARK|SPIELPLATZ~PLAYGROUND|KINO~CINEMA|THEATER~THEATRE|MUSEUM~MUSEUM|SCHWIMMBAD~SWIMMING POOL|STADION~STADIUM|RESTAURANT~RESTAURANT|HOTEL~HOTEL|POST~POST OFFICE|BANK~BANK|POLIZEI~POLICE STATION]]),
    },
    -- 20 Landschaften x 20 Naturelemente = 400 eindeutige Kartenbegriffe.
    NATURE = {
        code = "N", neutral = true,
        words = MakeCompounds({
            { de = "BERG", en = "MOUNTAIN" }, { de = "WALD", en = "FOREST" },
            { de = "FLUSS", en = "RIVER" }, { de = "SEE", en = "LAKE" },
            { de = "MEER", en = "SEA" }, { de = "KUESTEN", en = "COASTAL" },
            { de = "INSEL", en = "ISLAND" }, { de = "TAL", en = "VALLEY" },
            { de = "WIESEN", en = "MEADOW" }, { de = "WUESTEN", en = "DESERT" },
            { de = "MOOR", en = "MARSH" }, { de = "GLETSCHER", en = "GLACIER" },
            { de = "VULKAN", en = "VOLCANIC" }, { de = "HOEHLEN", en = "CAVE" },
            { de = "DSCHUNGEL", en = "JUNGLE" }, { de = "STEPPEN", en = "STEPPE" },
            { de = "SAVANNEN", en = "SAVANNA" }, { de = "KORALLEN", en = "CORAL" },
            { de = "POLAR", en = "POLAR" }, { de = "TROPEN", en = "TROPICAL" },
        }, {
            { de = "PFAD", en = "PATH" }, { de = "WEG", en = "TRAIL" },
            { de = "BODEN", en = "GROUND" }, { de = "STEIN", en = "STONE" },
            { de = "FELS", en = "ROCK" }, { de = "HANG", en = "SLOPE" },
            { de = "QUELLE", en = "SPRING" }, { de = "BACH", en = "STREAM" },
            { de = "UFER", en = "SHORE" }, { de = "WIESE", en = "MEADOW" },
            { de = "BLUME", en = "FLOWER" }, { de = "BAUM", en = "TREE" },
            { de = "BUSCH", en = "BUSH" }, { de = "MOOS", en = "MOSS" },
            { de = "NEBEL", en = "MIST" }, { de = "WIND", en = "WIND" },
            { de = "REGEN", en = "RAIN" }, { de = "SONNE", en = "SUN" },
            { de = "MOND", en = "MOON" }, { de = "STERN", en = "STAR" },
        }),
    },
    -- 20 Reiseziele x 20 Reisebegriffe = 400 eindeutige Kartenbegriffe.
    TRAVEL = {
        code = "T", neutral = true,
        words = MakeCompounds({
            { de = "STADT", en = "CITY" }, { de = "LAND", en = "COUNTRY" },
            { de = "INSEL", en = "ISLAND" }, { de = "KUESTEN", en = "COASTAL" },
            { de = "BERG", en = "MOUNTAIN" }, { de = "STRAND", en = "BEACH" },
            { de = "HAFEN", en = "HARBOUR" }, { de = "FLUGHAFEN", en = "AIRPORT" },
            { de = "BAHNHOF", en = "STATION" }, { de = "GRENZ", en = "BORDER" },
            { de = "WUESTEN", en = "DESERT" }, { de = "SEEN", en = "LAKE" },
            { de = "FLUSS", en = "RIVER" }, { de = "WALD", en = "FOREST" },
            { de = "DORF", en = "VILLAGE" }, { de = "ALTSTADT", en = "OLD TOWN" },
            { de = "MARKT", en = "MARKET" }, { de = "MUSEUM", en = "MUSEUM" },
            { de = "NATIONALPARK", en = "NATIONAL PARK" }, { de = "FERN", en = "DISTANT" },
        }, {
            { de = "REISE", en = "TRIP" }, { de = "TOUR", en = "TOUR" },
            { de = "KARTE", en = "MAP" }, { de = "PASS", en = "PASSPORT" },
            { de = "TICKET", en = "TICKET" }, { de = "KOFFER", en = "SUITCASE" },
            { de = "ROUTE", en = "ROUTE" }, { de = "ANREISE", en = "ARRIVAL" },
            { de = "ABREISE", en = "DEPARTURE" }, { de = "UEBERNACHTUNG", en = "OVERNIGHT STAY" },
            { de = "HOTEL", en = "HOTEL" }, { de = "HOSTEL", en = "HOSTEL" },
            { de = "CAMPING", en = "CAMPING" }, { de = "AUSFLUG", en = "EXCURSION" },
            { de = "STADTFUEHRER", en = "GUIDEBOOK" }, { de = "POSTKARTE", en = "POSTCARD" },
            { de = "SOUVENIR", en = "SOUVENIR" }, { de = "REISEFOTO", en = "TRAVEL PHOTO" },
            { de = "ABENTEUER", en = "ADVENTURE" }, { de = "FERNE", en = "DISTANCE" },
        }),
    },
}

function Sets:Normalize(id) return self.data[id] and id or "AZEROTH" end
function Sets:Get(id) return self.data[self:Normalize(id)] end
function Sets:GetCount(id) local set = self:Get(id); return set.words and #set.words or 0 end
function Sets:IsNeutral(id) return self:Get(id).neutral == true end

function Sets:GetWord(id, index, locale)
    local set = self:Get(id)
    local word = set.words and set.words[index]
    if set.localized then
        local catalogue = ArcadiaNexus.HGM_Words
        return catalogue and catalogue:GetLocalizedWord(word, locale) or "?"
    end
    return word and (word[locale] or word.enUS or word.deDE) or "?"
end

function Sets:GetOptions()
    local L = ArcadiaNexus.GetLocaleTable("SI7") or {}
    local options = {}
    for _, id in ipairs(self.order) do
        options[#options + 1] = { key = id, label = L["wordset_" .. string.lower(id)] or id,
            tooltip = L["wordset_" .. string.lower(id) .. "_tooltip"] or "" }
    end
    return options
end

-- 400 Begriffe pro neuem Set geben 16 volle Bretter ohne Kartenwiederholung.
-- Ein Beutel lebt nur beim Host; die gezogenen IDs selbst bleiben die einzige
-- Information, die an Mitspieler uebermittelt werden muss.
local everyday = Sets.data.EVERYDAY.words
local extras = ParsePairs([[BESEN~BROOM|EIMER~BUCKET|WISCHMOPP~MOP|STAUBSAUGER~VACUUM CLEANER|WASCHMASCHINE~WASHING MACHINE|TROCKNER~DRYER|WAESCHEKORB~LAUNDRY BASKET|KLEIDERBUeGEL~COAT HANGER|WASCHMITTEL~DETERGENT|SCHWAMM~SPONGE|PUTZMITTEL~CLEANER|MUeLLTONNE~BIN|MUeLLBEUTEL~BIN BAG|WAAGE~SCALES|NAeHMASCHINE~SEWING MACHINE|NADEL~NEEDLE|FADEN~THREAD|KNOPF~BUTTON|REISSVERSCHLUSS~ZIPPER|KLEIDERKLAMMER~CLOTHES PEG|EI~EGG|MILCH~MILK|JOGHURT~YOGHURT|MEHL~FLOUR|ZUCKER~SUGAR|SALZ~SALT|PFEFFER~PEPPER|OEL~OIL|ESSIG~VINEGAR|MARMELADE~JAM|WURST~SAUSAGE|FISCH~FISH|HUHN~CHICKEN|STEAK~STEAK|MAIS~CORN|BOHNE~BEAN|ERBSE~PEA|KOHl~CABBAGE|SPINAT~SPINACH|KURBIS~PUMPKIN|ANANAS~PINEAPPLE|PFIRSICH~PEACH|MANGO~MANGO|KIWI~KIWI|BLAUBEERE~BLUEBERRY|HIMBEERE~RASPBERRY|WASSERMELONE~WATERMELON|CROISSANT~CROISSANT|MUeSLI~MUESLI|SCHOKOLADE~CHOCOLATE|PULLOVER~JUMPER|T-SHIRT~T-SHIRT|SHORTS~SHORTS|ANZUG~SUIT|KRAWATTE~TIE|BLUSE~BLOUSE|WESTE~VEST|PYJAMA~PYJAMAS|HAUSSCHUH~SLIPPER|SANDALEN~SANDALS|TURNschuh~TRAINER|RING~RING|KETTE~NECKLACE|OHRRING~EARRING|ARMBAND~BRACELET|GELDBEUTEL~WALLET|KOFFer~SUITCASE|REGENJACKE~RAINCOAT|SONNENBRILLE~SUNGLASSES|KAPUZE~HOOD|ZEITUNG~NEWSPAPER|ZEITSCHRIFT~MAGAZINE|LESEZEICHEN~BOOKMARK|BRIEF~LETTER|POSTKARTE~POSTCARD|UMSCHLAG~ENVELOPE|STEMPEL~STAMP|RECHNER~CALCULATOR|LOCHER~HOLE PUNCH|HEFTER~STAPLER|KLAMMER~PAPER CLIP|NOTIZZETTEL~STICKY NOTE|TAGEBUCH~DIARY|KALENDER~CALENDAR|GLOBUS~GLOBE|WANDKARTE~WALL MAP|LABOR~LABORATORY|WERKSTATT~WORKSHOP|BAUSTELLE~BUILDING SITE|BAECKEREI~BAKERY|BLUMENLADEN~FLOWER SHOP|TIERARZT~VET|RATHAUS~TOWN HALL|GERICHT~COURTHOUSE|FEUERWACHE~FIRE STATION|TANKSTELLE~PETROL STATION|ZOO~ZOO|AQUARIUM~AQUARIUM|STRAND~BEACH|CAMPINGPLATZ~CAMPSITE|BAHNGLEIS~PLATFORM|FAHRKARTE~TICKET|LENKRAD~STEERING WHEEL|SICHERHEITSGURT~SEATBELT|KOFFERraum~BOOT|MOTOR~ENGINE|REIFEN~TYRE|BREMSEN~BRAKES|FAHRPLAN~TIMETABLE|FAHRRADSATTEL~BICYCLE SEAT|FAHRRADHELM~BICYCLE HELMET|ANHÄNGER~TRAILER|KREUZFAHRT~CRUISE|SEGEL~SAIL|ANKER~ANCHOR|RETTUNGSBOOT~LIFEBOAT|BORDKARTE~BOARDING PASS|GEPaeCK~LUGGAGE|ROLLTREPPE~ESCALATOR|AUFZUG~LIFT|PASSWORT~PASSWORD|INTERNET~INTERNET|WEBSEITE~WEBSITE|E-MAIL~EMAIL|NACHRICHT~MESSAGE|VIDEO~VIDEO|SPIELKONSOLE~GAME CONSOLE|JOYSTICK~JOYSTICK|ROUTER~ROUTER|WLAN~WIFI|USB-STICK~USB STICK|FESTPLATTE~HARD DRIVE|APP~APP|DATEI~FILE|ORDNERSTRUKTUR~DIRECTORY|SCHLAGZEUG~DRUMS|GITARRE~GUITAR|KLAVIER~PIANO|GEIGE~VIOLIN|FLÖTE~FLUTE|TROMPETE~TRUMPET|MIKROFONSTÄNDER~MICROPHONE STAND|NOTEN~SHEET MUSIC|TANZ~DANCE|FUSSBALL~FOOTBALL|TENNIS~TENNIS|BASKETBALL~BASKETBALL|VOLLEYBALL~VOLLEYBALL|SCHLÄGER~RACKET|BALL~BALL|TOR~GOAL|POKAL~TROPHY|MEDAILLE~MEDAL|SCHWIMMBRILLE~GOGGLES|SKI~SKIS|SCHLITTEN~SLEDGE|YOGAMATTE~YOGA MAT|PUZZLE~PUZZLE|SCHACH~CHESS|WÜRFEL~DICE|KARTENSPIEL~CARD GAME|TEDDYBÄR~TEDDY BEAR|PUPPE~DOLL|BAUSTEIN~BUILDING BLOCK|LUFTBALLON~BALLOON|Drachen~KITE|FERNGLAS~BINOCULARS|LUPE~MAGNIFYING GLASS|FOTOALBUM~PHOTO ALBUM|GEBURTSTAG~BIRTHDAY|GESCHENK~PRESENT|PARTY~PARTY|KONFETTI~CONFETTI|EINLADUNG~INVITATION|HOCHZEIT~WEDDING|KUCHENKERZE~BIRTHDAY CANDLE|FEUERWERK~FIREWORKS|SCHNEEMANN~SNOWMAN|SONNENSCHIRM~PARASOL|GRILL~BARBECUE|PICKNICK~PICNIC|ZELT~TENT|SCHLAFSACK~SLEEPING BAG|FEUERSTELLE~CAMPFIRE|GARTEN~GARDEN|RASEN~LAWN|HEGGE~HEDGE|ZAUN~FENCE|SCHAUFEL~SHOVEL|GIESSKANNE~WATERING CAN|BLUMENTOPF~FLOWER POT|SAMEN~SEEDS|LEITER~LADDER|HAMMER~HAMMER|SCHRAUBENZIEHER~SCREWDRIVER|ZANGE~PLIERS|SCHRAUBE~SCREW|NAGEL~NAIL|SÄGE~SAW|BOHRMASCHINE~DRILL|WERKBANK~WORKBENCH|MASSBAND~TAPE MEASURE|SCHUTZHELM~HARD HAT|TÜRKLINKe~DOOR HANDLE|HAUSTIER~PET|HUND~DOG|KATZE~CAT|GOLDFISCH~GOLDFISH|KANINCHEN~RABBIT|HAMSTER~HAMSTER|VOGELKAEFIG~BIRD CAGE|FUTTERNAPF~FOOD BOWL|LEINE~LEASH|KRATZBAUM~SCRATCHING POST|TIERDECKE~PET BLANKET|AUGENARZT~OPTICIAN|FRISEUR~HAIRDRESSER|KASSIERER~CASHIER|MECHANIKER~MECHANIC|ARCHITEKT~ARCHITECT|ANWALT~LAWYER|FORSCHER~SCIENTIST|JOURNALIST~JOURNALIST|FOTOGRAF~PHOTOGRAPHER|BIBLIOTHEKAR~LIBRARIAN|REINIGUNGSKRAFT~CLEANER|BRIEFTASCHE~BRIEFCASE|VISITENKARTE~BUSINESS CARD|KAFFEEPAUSE~COFFEE BREAK|MITTAGESSEN~LUNCH|BESPRECHUNG~MEETING|AUFGABE~TASK|PAUSE~BREAK|SCHICHT~SHIFT|GEHALT~SALARY|FERIEN~HOLIDAY]] )
for _, word in ipairs(extras) do everyday[#everyday + 1] = word end
while #everyday > 400 do table.remove(everyday) end

Sets._bags = {}
function Sets:TakeBoard(id)
    id = self:Normalize(id)
    local count = self:GetCount(id)
    local bag = self._bags[id]
    if not bag or bag.pos + 24 > #bag.ids then
        local ids = {}
        for i = 1, count do ids[i] = i end
        ArcadiaNexus.ArrayUtils.Shuffle(ids)
        bag = { ids = ids, pos = 1 }
        self._bags[id] = bag
    end
    local board = {}
    for i = 1, 25 do board[i] = bag.ids[bag.pos + i - 1] end
    bag.pos = bag.pos + 25
    return board
end
