-- Generated by _tools/gen_dmp_assets.py. Address by kind + state.
ArcadiaNexus.DMP_Assets = {
    ROOT = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\",
    ball = {
        base = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\ball_base",
        highlight = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\ball_highlight",
    },
    bumper = {
        idle = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\bumper_idle",
        hit_01 = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\bumper_hit_01",
        hit_02 = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\bumper_hit_02",
        lit = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\bumper_lit",
    },
    target = {
        idle = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\target_idle",
        active = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\target_active",
        hit = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\target_hit",
    },
    light = {
        off = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\light_off",
        on = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\light_on",
        flash = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\light_flash",
    },
    flipper = {
        base = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\flipper_base",
        base_right = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\flipper_base_right",
        activeGlow = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\flipper_activeGlow",
        activeGlow_right = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\flipper_activeGlow_right",
    },
    kickback = {
        idle = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\kickback_idle",
        armed = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\kickback_armed",
        fire = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\kickback_fire",
    },
    lane = {
        off = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\lane_off",
        lit = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\lane_lit",
        completed = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\lane_completed",
    },
    slingshot = {
        base = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\slingshot",
    },
    arrow = {
        base = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\arrow",
    },
    post = {
        base = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\post",
    },
    playfield = {
        midway = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\playfield\\midway_bg",
        carousel = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\playfield\\carousel_bg",
    },
    fx = {
        ring = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\fx\\ring",
        glow = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\fx\\glow",
    },
    plunger = {
        spring = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\plunger_spring",
        knob = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\plunger_knob",
    },
    eye = {
        sclera = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\eye_sclera",
        pupil = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\eye_pupil",
        lid = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\sprites\\eye_lid",
    },
    chrome = {
        logo = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\logo\\logo_dp",
        border = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\border\\border_dp",
        bg = "Interface\\AddOns\\ArcadiaNexus\\Games\\DarkmoonPinball\\assets\\background\\background_dp",
    },
}

function ArcadiaNexus.DMP_Assets.Get(kind, state)
    local pack = ArcadiaNexus.DMP_Assets[kind]
    if type(pack) ~= "table" then return nil end
    return pack[state] or pack.idle or pack.base or pack.off or pack.midway
end

