--[[
    ArcadiaNexus – Bubble Shooter
    Games/BubbleShooter/Language.lua
    Zugriff: ArcadiaNexus.GetLocaleTable("BUBBLESHOOTER")
]]

ArcadiaNexus.RegisterLocale("BUBBLESHOOTER", "deDE", {
    game_title = "Arcane Barrage",

    btn_start        = "Spiel starten",
    btn_exit         = "Beenden",
    btn_new_game     = "Neues Spiel",
    btn_next_level   = "Nächstes Level",
    btn_level_select = "Neu starten",
    btn_continue     = "Fortfahren",

    mode_endless = "Endlos",
    mode_time    = "Zeit",
    mode_shot    = "Kampagne",
    diff_easy    = "Einfach",
    diff_normal  = "Normal",
    diff_hard    = "Schwer",

    menu_title               = "Arcane Barrage",
    slot_info                = "Level %d · %s",
    slot_paused              = "pausiert",
    hint_select_slot         = "Wähle einen Speicherslot",
    map_title                = "%s · Level %d–%d",
    map_stars_total          = "Sterne: %d / %d",
    map_region_01            = "Leylinien-Ursprung",
    map_region_02            = "Kristallkavernen",
    map_region_03            = "Zerbrochene Sternwarte",
    map_region_04            = "Smaragdriss",
    map_region_05            = "Glutspalte",
    map_region_06            = "Leerenarchipel",
    map_region_07            = "Sternenzitadelle",
    map_region_08            = "Frostgipfel",
    map_region_09            = "Traumwald",
    map_region_10            = "Arkane Krone",
    confirm_overwrite        = "Spielstand überschreiben?",
    confirm_overwrite_body   = "Slot %d enthält einen Spielstand.",
    confirm_delete           = "Spielstand wirklich löschen?",
    confirm_delete_body      = "Slot %d wird geleert.",

    lbl_score      = "Punkte",
    lbl_highscore  = "Best",
    lbl_level      = "Level",
    lbl_shots      = "Schüsse",
    lbl_time       = "Zeit",
    lbl_combo      = "Kombo",
    lbl_power      = "Macht",
    lbl_miss       = "Fehler",
    lbl_overcharge = "OVERCHARGE",
    lbl_next       = "NEXT",

    hint_idle   = "|cffaaaaaa Modus und Schwierigkeit wählen, dann starten.\nZielen mit der Maus, klicken zum Schießen.|r",
    hint_joker  = "Joker: klicke eine Kugel auf dem Feld, um ihre Farbe zu übernehmen.",
    hint_power  = "Macht bereit: %s",

    power_joker      = "Joker",
    power_bomb       = "Bombe",
    power_lightning  = "Kettenblitz",
    power_dragonfire = "Drachenfeuer",

    drop_small   = "DROP!",
    drop_chain   = "CHAIN DROP!",
    drop_massive = "MASSIVE DROP!",
    drop_arcane  = "ARCANE COLLAPSE!",
    combo_basic   = "KOMBO x%d",
    combo_arcane  = "ARKANE KOMBO x%d",
    combo_surge   = "LEY-SCHUB x%d",
    combo_barrage = "ARKANE SALVE x%d",

    result_level_win_title = "|cff40ff40Level geschafft!|r",
    result_final_win_title = "|cffffd700Kampagne geschafft!|r",
    result_loss_title      = "|cffff4444Spiel vorbei!|r",
    result_time_title      = "|cffff8800Zeit abgelaufen!|r",
    result_level           = "|cffaaaaaa Level:|r |cffffff00%d|r",
    result_shots           = "|cffaaaaaa Schüsse:|r |cffffff00%d|r",
    result_combo           = "|cffaaaaaa Max. Kombo:|r |cffffff00x%d|r",
    result_drop            = "|cffaaaaaa Größter Fall:|r |cffffff00%d|r",

    box_sounds = "Sound",
    box_theme  = "Thema",
    box_guide  = "Anleitung",
    box_visuals = "Visuelles",
    sound_enabled    = "Sounds aktiviert",
    sound_shoot      = "Schuss",
    sound_pop        = "Platzen",
    sound_drop       = "Cluster-Fall",
    sound_power      = "Macht",
    sound_overcharge = "Overcharge",
    sound_win        = "Sieg",
    sound_lose       = "Niederlage",
    lbl_screen_flash = "Bildschirmblitz",
    lbl_colorblind   = "Farbblind-Modus",
    lbl_theme_prev   = "Vorschau:",
    theme_energies   = "Leylinien",
    theme_raidmarker = "Schlachtzug",
    theme_gems       = "Juwelen",
    color_ley    = "Ley",
    color_fel    = "Teufel",
    color_light  = "Licht",
    color_frost  = "Frost",
    color_ember  = "Glut",
    color_void   = "Leere",

    guide_goal     = "|cffffff00Ziel:|r Schieße Energien in das Hex-Feld. Drei gleiche, die zusammenhängen, platzen. Alles, was nicht mehr an der Decke hängt, fällt – das sind die großen Punkte.",
    guide_aim      = "|cffffff00Zielen:|r Maus zeigt die Bahn. Einfach: lange Linie plus erster Abpraller. Normal: kurze Linie plus Abpraller. Schwer: kurze Linie ohne Bounce-Vorschau.",
    guide_modes    = "|cffffff00Modi:|r Endlos – Seed-Feld, nach Fehlschüssen neue Reihe von oben. Zeit – 120 Sekunden, große Gruppen geben Zeit zurück. Kampagne – 100 Level mit Schusslimit, generiert und geprüft.",
    guide_combo    = "|cffffff00Kombo:|r Jeder Treffer mit Explosion erhöht den Multiplikator. Ein Fehlschuss setzt ihn zurück. Kugel 10, fallende Kugel 25, danach × Kombo.",
    guide_power    = "|cffffff00Machtleiste:|r Erfolgreiche Schüsse füllen Energie. Bei 100 % eine zufällige Macht: Joker, Bombe, Kettenblitz oder Drachenfeuer.",
    guide_over     = "|cffffff00Overcharge:|r Fünf erfolgreiche Schüsse hintereinander – 10 Sekunden doppelte Punkte und schnellere Machtleiste. Match bleibt bei drei.",
    guide_drop     = "|cffffff00Drop:|r Große herabfallende Cluster lösen Fanfaren aus (CHAIN DROP, MASSIVE DROP, ARCANE COLLAPSE).",
    guide_slots    = "|cffaaaaaa Die Kampagne speichert den Zwischenstand in Slots. Endlos und Zeit starten immer neu.|r",
    guide_color    = "|cffffff00Farbblind-Modus:|r In den Visuals-Einstellungen. Jede Energie bekommt eine eigene Marke (Strich, Plus, Dreieck, Quadrat, Punkt, Kreuz).",

    lb_endless_easy   = "Endlos · Einfach",
    lb_endless_normal = "Endlos · Normal",
    lb_endless_hard   = "Endlos · Schwer",
    lb_time_easy      = "Zeit · Einfach",
    lb_time_normal    = "Zeit · Normal",
    lb_time_hard      = "Zeit · Schwer",
    lb_shot_easy      = "Kampagne · Einfach",
    lb_shot_normal    = "Kampagne · Normal",
    lb_shot_hard      = "Kampagne · Schwer",
    lb_max_combo      = "Beste Kombo",
    lb_max_drop       = "Größter Fall",

    btn_reset = "Reset",
    lvl_01 = "Erste Funken",
    lvl_02 = "Zwei Bänder",
    lvl_03 = "Ley-Gitter",
    lvl_04 = "Vier Tore",
    lvl_05 = "Hängende Brücke",
    lvl_06 = "Farbfalle",
    lvl_07 = "Splitterkrone",
    lvl_08 = "Kettennetz",
    lvl_09 = "Sechs Ströme",
    lvl_10 = "Arkaner Einsturz",
    lvl_11 = "Deckennetz",
    lvl_12 = "Nadelöhr",
    lvl_13 = "Sechs auf Acht",
    lvl_gen = "Barrage %d",
})

ArcadiaNexus.RegisterLocale("BUBBLESHOOTER", "enUS", {
    game_title = "Arcane Barrage",

    btn_start        = "Start Game",
    btn_exit         = "Exit",
    btn_new_game     = "New Game",
    btn_next_level   = "Next Level",
    btn_level_select = "Restart Run",
    btn_continue     = "Continue",

    mode_endless = "Endless",
    mode_time    = "Time",
    mode_shot    = "Campaign",
    diff_easy    = "Easy",
    diff_normal  = "Normal",
    diff_hard    = "Hard",

    menu_title               = "Arcane Barrage",
    slot_info                = "Level %d · %s",
    slot_paused              = "paused",
    hint_select_slot         = "Choose a save slot",
    map_title                = "%s · Level %d–%d",
    map_stars_total          = "Stars: %d / %d",
    map_region_01            = "Leyline Origin",
    map_region_02            = "Crystal Caverns",
    map_region_03            = "Shattered Observatory",
    map_region_04            = "Emerald Rift",
    map_region_05            = "Ember Chasm",
    map_region_06            = "Void Archipelago",
    map_region_07            = "Star Citadel",
    map_region_08            = "Frost Peaks",
    map_region_09            = "Dreamwood",
    map_region_10            = "Arcane Crown",
    confirm_overwrite        = "Overwrite save?",
    confirm_overwrite_body   = "Slot %d already has a save.",
    confirm_delete           = "Delete this save?",
    confirm_delete_body      = "Slot %d will be cleared.",

    lbl_score      = "Score",
    lbl_highscore  = "Best",
    lbl_level      = "Level",
    lbl_shots      = "Shots",
    lbl_time       = "Time",
    lbl_combo      = "Combo",
    lbl_power      = "Power",
    lbl_miss       = "Misses",
    lbl_overcharge = "OVERCHARGE",
    lbl_next       = "NEXT",

    hint_idle   = "|cffaaaaaa Pick a mode and difficulty, then start.\nAim with the mouse, click to shoot.|r",
    hint_joker  = "Joker: click a board bubble to take its color.",
    hint_power  = "Power ready: %s",

    power_joker      = "Joker",
    power_bomb       = "Bomb",
    power_lightning  = "Chain Lightning",
    power_dragonfire = "Dragonfire",

    drop_small   = "DROP!",
    drop_chain   = "CHAIN DROP!",
    drop_massive = "MASSIVE DROP!",
    drop_arcane  = "ARCANE COLLAPSE!",
    combo_basic   = "COMBO x%d",
    combo_arcane  = "ARCANE COMBO x%d",
    combo_surge   = "LEY SURGE x%d",
    combo_barrage = "ARCANE BARRAGE x%d",

    result_level_win_title = "|cff40ff40Level cleared!|r",
    result_final_win_title = "|cffffd700Campaign complete!|r",
    result_loss_title      = "|cffff4444Game Over!|r",
    result_time_title      = "|cffff8800Time's up!|r",
    result_level           = "|cffaaaaaa Level:|r |cffffff00%d|r",
    result_shots           = "|cffaaaaaa Shots:|r |cffffff00%d|r",
    result_combo           = "|cffaaaaaa Best combo:|r |cffffff00x%d|r",
    result_drop            = "|cffaaaaaa Biggest drop:|r |cffffff00%d|r",

    box_sounds = "Sound",
    box_theme  = "Theme",
    box_guide  = "Guide",
    box_visuals = "Visuals",
    sound_enabled    = "Sounds enabled",
    sound_shoot      = "Shot",
    sound_pop        = "Pop",
    sound_drop       = "Cluster drop",
    sound_power      = "Power",
    sound_overcharge = "Overcharge",
    sound_win        = "Win",
    sound_lose       = "Defeat",
    lbl_screen_flash = "Screen flash",
    lbl_colorblind   = "Colorblind mode",
    lbl_theme_prev   = "Preview:",
    theme_energies   = "Ley Lines",
    theme_raidmarker = "Raid Markers",
    theme_gems       = "Jewels",
    color_ley    = "Ley",
    color_fel    = "Fel",
    color_light  = "Light",
    color_frost  = "Frost",
    color_ember  = "Ember",
    color_void   = "Void",

    guide_goal     = "|cffffff00Goal:|r Shoot orbs into the hex field. Three connected matching colors pop. Anything no longer hanging from the ceiling drops — that's the big score.",
    guide_aim      = "|cffffff00Aim:|r The mouse shows the path. Easy: long line plus first bounce. Normal: short line plus bounce. Hard: short line, no bounce preview.",
    guide_modes    = "|cffffff00Modes:|r Endless — seeded board, missed shots spawn a new top row. Time — 120 seconds, big groups add time back. Campaign — 100 shot-limit levels, generated and validated.",
    guide_combo    = "|cffffff00Combo:|r Every exploding shot raises the multiplier. A miss resets it. Orb 10, falling orb 25, then × combo.",
    guide_power    = "|cffffff00Power bar:|r Successful shots fill energy. At 100% you get a random power: Joker, Bomb, Chain Lightning, or Dragonfire.",
    guide_over     = "|cffffff00Overcharge:|r Five successful shots in a row — 10 seconds of double score and a faster power bar. Matches still need three.",
    guide_drop     = "|cffffff00Drop:|r Large falling clusters trigger fanfares (CHAIN DROP, MASSIVE DROP, ARCANE COLLAPSE).",
    guide_slots    = "|cffaaaaaa Campaign progress is stored in save slots. Endless and Time always start fresh.|r",
    guide_color    = "|cffffff00Colorblind mode:|r In Visual settings. Each energy gets its own mark (dash, plus, triangle, square, dot, cross).",

    lb_endless_easy   = "Endless · Easy",
    lb_endless_normal = "Endless · Normal",
    lb_endless_hard   = "Endless · Hard",
    lb_time_easy      = "Time · Easy",
    lb_time_normal    = "Time · Normal",
    lb_time_hard      = "Time · Hard",
    lb_shot_easy      = "Campaign · Easy",
    lb_shot_normal    = "Campaign · Normal",
    lb_shot_hard      = "Campaign · Hard",
    lb_max_combo      = "Best combo",
    lb_max_drop       = "Biggest drop",

    btn_reset = "Reset",
    lvl_01 = "First Sparks",
    lvl_02 = "Twin Bands",
    lvl_03 = "Ley Lattice",
    lvl_04 = "Four Gates",
    lvl_05 = "Hanging Bridge",
    lvl_06 = "Color Trap",
    lvl_07 = "Shard Crown",
    lvl_08 = "Chain Net",
    lvl_09 = "Six Currents",
    lvl_10 = "Arcane Collapse",
    lvl_11 = "Ceiling Net",
    lvl_12 = "Needle Gate",
    lvl_13 = "Six on Eight",
    lvl_gen = "Barrage %d",
})
