-- ============================================================
--  Azeroth's Tiny Guardians – Language.lua
--  Lokalisierung deDE / enUS
-- ============================================================

local ArcadiaNexus = _G.ArcadiaNexus

ArcadiaNexus.RegisterLocale("AZEROTHTINYGUARDIANS", "deDE", {
    game_title     = "Azeroth's Tiny Guardians",

    pet_murloc     = "Baby Murloc",
    pet_dragon     = "Drachenwelpe",
    pet_undead     = "Kleiner Untoter",
    pet_mechagnome = "Mechagnome-Robot",
    pet_frostwolf  = "Frostwolf-Welpe",
    pet_quilboar   = "Junger Quilboar",

    stage_baby     = "Baby",
    stage_youth    = "Jugend",
    stage_adult    = "Erwachsen",

    need_hunger    = "Hunger",
    need_happiness = "Glück",
    need_energy    = "Energie",
    need_health    = "Gesundheit",
    need_hygiene   = "Sauberkeit",

    btn_feed       = "Füttern",
    btn_sleep      = "Schlafen",
    btn_wash       = "Baden",
    btn_train      = "Trainieren",
    btn_heal       = "Heilen",
    btn_pet        = "Streicheln",
    btn_adopt      = "Adoptieren",
    btn_stall      = "Stall",
    btn_retire     = "In den Ruhestand schicken",
    btn_start      = "Spiel starten",
    btn_stop       = "Beenden",
    btn_care       = "Pflegen",
    btn_new_pet    = "Neues Pet",
    btn_dev_evolve = "Nächste Stufe (Dev)",
    btn_dev_evolve_reset = "Baby (Dev)",
    lbl_pet_name   = "Name",
    lbl_living     = "In Pflege",
    lbl_retired    = "Ruhestand",

    state_adopting = "Wähle deinen Begleiter!",
    state_sleeping = "Schläft gerade...",
    state_evolving = "Entwickelt sich!",
    state_active   = "Pet aktiv",

    lbl_xp           = "XP",
    lbl_evolution    = "Nächste Evolution",
    lbl_stall        = "Stall",
    lbl_cooldown     = "Bereit in",
    lbl_adopt_hint   = "Klicke auf ein Pet, um es zu adoptieren.",
    lbl_name_hint    = "Gib deinem Pet einen Namen.",
    btn_back         = "Zurück",
    btn_confirm      = "Bestätigen",
    btn_cancel       = "Abbrechen",
    btn_ok           = "OK",
    confirm_retire   = "Pet wirklich in den Ruhestand schicken? Es bleibt im Stall sichtbar.",
    title_release    = "Freilassen",
    confirm_release  = "Willst du %s wirklich freilassen? Das Pet geht verloren.",
    title_pet_limit  = "Stall voll",
    msg_pet_limit    = "Du hast die maximale Anzahl von %d Pets erreicht. Lass zuerst eines frei, bevor du ein neues adoptierst.",
    lbl_stall_empty  = "Noch keine Pets im Stall. Adoptiere ein neues Pet!",
    lbl_retired_on   = "Aufgezogen am",
    lbl_stall_count  = "Pets im Stall",
    lbl_stall_detail = "Stall-Details",
    lbl_species      = "Art",
    lbl_status       = "Status",
    lbl_stage        = "Stufe",
    lbl_xp_full      = "Erfahrung",
    lbl_care         = "Pflege",
    lbl_fed          = "Gefüttert",
    lbl_washed       = "Gewaschen",
    lbl_trained      = "Trainiert",
    lbl_petted       = "Gestreichelt",
    lbl_healed       = "Geheilt",
    lbl_slept        = "Schlafphasen",
    dev_layout_hint  = "DevMode: Layout-Rahmen",

    err_cooldown     = "Noch nicht bereit.",
    err_sleeping     = "Pet schläft.",
    err_too_tired    = "Zu müde zum Trainieren.",
    err_train_sad    = "Zu traurig zum Trainieren.",

    trait_greedy        = "Verfressen",
    trait_picky         = "Pingelig",
    trait_warrior       = "Krieger",
    trait_clingy        = "Anhänglich",
    trait_hypochondriac = "Hypochonder",
    trait_lazy          = "Faulpelz",
    trait_balanced      = "Ausgeglichen",

    lbl_traits = "Persönlichkeit",

    title_murloc_default = "Mrgl",
    title_murloc_greedy = "Mrgl der Gefräßige",
    title_murloc_picky = "Mrgl der Pingelige",
    title_murloc_warrior = "Mrgl der Tapfere",
    title_murloc_clingy = "Mrgl der Anhängliche",
    title_murloc_hypochondriac = "Mrgl der Beklommene",
    title_murloc_lazy = "Mrgl der Faule",
    title_murloc_balanced = "Mrgl der Ausgeglichene",

    title_dragon_default = "Ember",
    title_dragon_greedy = "Gefräßiger Drachenwelpe",
    title_dragon_picky = "Pingeliger Drachenwelpe",
    title_dragon_warrior = "Sturmdrachenwächter",
    title_dragon_clingy = "Anhänglicher Drachenwelpe",
    title_dragon_hypochondriac = "Bekümmerter Drachenwelpe",
    title_dragon_lazy = "Träger Drachenwelpe",
    title_dragon_balanced = "Edler Drachenwelpe",

    title_undead_default = "Rotgrins",
    title_undead_greedy = "Gefräßiger Untoter",
    title_undead_picky = "Pingeliger Untoter",
    title_undead_warrior = "Untoter Krieger",
    title_undead_clingy = "Anhänglicher Untoter",
    title_undead_hypochondriac = "Hypochondrischer Untoter",
    title_undead_lazy = "Fauliger Begleiter",
    title_undead_balanced = "Ausgeglichener Untoter",

    title_mechagnome_default = "Bolts",
    title_mechagnome_greedy = "Bolts XL-Futtermodul",
    title_mechagnome_picky = "Bolts Reinigungsprotokoll",
    title_mechagnome_warrior = "Bolts Kampfeinheit",
    title_mechagnome_clingy = "Bolts Bindungsmodul",
    title_mechagnome_hypochondriac = "Bolts Diagnose-Bot",
    title_mechagnome_lazy = "Bolts Energiesparmodus",
    title_mechagnome_balanced = "Nexus-Protokoll 7",

    title_frostwolf_default = "Snowpaw",
    title_frostwolf_greedy = "Gefräßiger Frostwolf",
    title_frostwolf_picky = "Pingeliger Frostwolf",
    title_frostwolf_warrior = "Frostwolf-Krieger",
    title_frostwolf_clingy = "Treuer Frostwolf",
    title_frostwolf_hypochondriac = "Bekümmerter Frostwolf",
    title_frostwolf_lazy = "Fauler Frostwolf",
    title_frostwolf_balanced = "Loyaler Frostwolf",

    title_quilboar_default = "Spike",
    title_quilboar_greedy = "Gefräßiger Quilboar",
    title_quilboar_picky = "Pingeliger Quilboar",
    title_quilboar_warrior = "Sturköpfiger Quilboar",
    title_quilboar_clingy = "Anhänglicher Quilboar",
    title_quilboar_hypochondriac = "Bekümmerter Quilboar",
    title_quilboar_lazy = "Fauler Quilboar",
    title_quilboar_balanced = "Ausgeglichener Quilboar",

    box_sounds       = "Sound",
    box_visual       = "Visuelles",
    box_guide        = "Anleitung",
    box_stall        = "Stall",
    sound_enabled    = "Sound aktiviert",
    sound_interact   = "Interaktions-Ton",
    sound_evolve     = "Evolutions-Ton",
    sound_comment    = "Kommentar-Ton",
    lbl_show_bubbles = "Sprechblasen anzeigen",
    lbl_show_emotes  = "Emotionen anzeigen",
    btn_reset        = "Reset",

    guide_1 = "Starte das Spiel und wähle eines von 6 Pets.",
    guide_2 = "Erfülle die 5 Bedürfnisse: Hunger, Glück, Energie, Gesundheit, Sauberkeit.",
    guide_3 = "Nutze 6 Interaktionen — jede hat einen Cooldown.",
    guide_4 = "Sammle XP durch Interaktionen (hohes Glück = mehr XP).",
    guide_5 = "Evolviere bei 200 XP (Jugend) und 600 XP (Erwachsen).",
    guide_6 = "Dein Spielstil formt die Persönlichkeit deines Pets.",
    guide_7 = "Im Stall wechselst du zwischen deinen Pets oder adoptierst neue.",
    guide_8 = "Erwachsene Pets können in den Ruhestand geschickt werden.",
})

ArcadiaNexus.RegisterLocale("AZEROTHTINYGUARDIANS", "enUS", {
    game_title     = "Azeroth's Tiny Guardians",

    pet_murloc     = "Baby Murloc",
    pet_dragon     = "Dragon Whelp",
    pet_undead     = "Tiny Undead",
    pet_mechagnome = "Mechagnome Bot",
    pet_frostwolf  = "Frostwolf Pup",
    pet_quilboar   = "Young Quilboar",

    stage_baby     = "Baby",
    stage_youth    = "Youth",
    stage_adult    = "Adult",

    need_hunger    = "Hunger",
    need_happiness = "Happiness",
    need_energy    = "Energy",
    need_health    = "Health",
    need_hygiene   = "Hygiene",

    btn_feed       = "Feed",
    btn_sleep      = "Sleep",
    btn_wash       = "Wash",
    btn_train      = "Train",
    btn_heal       = "Heal",
    btn_pet        = "Pet",
    btn_adopt      = "Adopt",
    btn_stall      = "Stable",
    btn_retire     = "Retire",
    btn_start      = "Start Game",
    btn_stop       = "Quit",
    btn_care       = "Care",
    btn_new_pet    = "New Pet",
    btn_dev_evolve = "Next stage (Dev)",
    btn_dev_evolve_reset = "Baby (Dev)",
    lbl_pet_name   = "Name",
    lbl_living     = "In care",
    lbl_retired    = "Retired",

    state_adopting = "Choose your companion!",
    state_sleeping = "Sleeping...",
    state_evolving = "Evolving!",
    state_active   = "Pet active",

    lbl_xp           = "XP",
    lbl_evolution    = "Next evolution",
    lbl_stall        = "Stable",
    lbl_cooldown     = "Ready in",
    lbl_adopt_hint   = "Click a pet to adopt it.",
    lbl_name_hint    = "Give your pet a name.",
    btn_back         = "Back",
    btn_confirm      = "Confirm",
    btn_cancel       = "Cancel",
    btn_ok           = "OK",
    confirm_retire   = "Retire this pet? It will remain visible in the stable.",
    title_release    = "Release",
    confirm_release  = "Really release %s? This pet will be gone for good.",
    title_pet_limit  = "Stable full",
    msg_pet_limit    = "You already have the maximum of %d pets. Release one before adopting another.",
    lbl_stall_empty  = "No pets in the stable yet. Adopt a new companion!",
    lbl_retired_on   = "Raised on",
    lbl_stall_count  = "Pets in stable",
    lbl_stall_detail = "Stable details",
    lbl_species      = "Species",
    lbl_status       = "Status",
    lbl_stage        = "Stage",
    lbl_xp_full      = "Experience",
    lbl_care         = "Care",
    lbl_fed          = "Fed",
    lbl_washed       = "Washed",
    lbl_trained      = "Trained",
    lbl_petted       = "Petted",
    lbl_healed       = "Healed",
    lbl_slept        = "Sleep sessions",
    dev_layout_hint  = "DevMode: layout frames",

    err_cooldown     = "Not ready yet.",
    err_sleeping     = "Pet is sleeping.",
    err_too_tired    = "Too tired to train.",
    err_train_sad    = "Too sad to train.",

    trait_greedy        = "Greedy",
    trait_picky         = "Picky",
    trait_warrior       = "Warrior",
    trait_clingy        = "Clingy",
    trait_hypochondriac = "Hypochondriac",
    trait_lazy          = "Lazy",
    trait_balanced      = "Balanced",

    lbl_traits = "Personality",

    title_murloc_default = "Mrgl",
    title_murloc_greedy = "Mrgl the Ravenous",
    title_murloc_picky = "Mrgl the Fussy",
    title_murloc_warrior = "Mrgl the Brave",
    title_murloc_clingy = "Mrgl the Clingy",
    title_murloc_hypochondriac = "Mrgl the Anxious",
    title_murloc_lazy = "Mrgl the Lazy",
    title_murloc_balanced = "Mrgl the Balanced",

    title_dragon_default = "Ember",
    title_dragon_greedy = "Ravenous Whelp",
    title_dragon_picky = "Fussy Whelp",
    title_dragon_warrior = "Storm Dragon Warden",
    title_dragon_clingy = "Clingy Whelp",
    title_dragon_hypochondriac = "Anxious Whelp",
    title_dragon_lazy = "Sluggish Whelp",
    title_dragon_balanced = "Noble Whelp",

    title_undead_default = "Rotgrins",
    title_undead_greedy = "Ravenous Undead",
    title_undead_picky = "Fussy Undead",
    title_undead_warrior = "Undead Warrior",
    title_undead_clingy = "Clingy Undead",
    title_undead_hypochondriac = "Hypochondriac Undead",
    title_undead_lazy = "Lazy Companion",
    title_undead_balanced = "Balanced Undead",

    title_mechagnome_default = "Bolts",
    title_mechagnome_greedy = "Bolts XL Feeder Module",
    title_mechagnome_picky = "Bolts Cleaning Protocol",
    title_mechagnome_warrior = "Bolts Combat Unit",
    title_mechagnome_clingy = "Bolts Bond Module",
    title_mechagnome_hypochondriac = "Bolts Diagnostic Bot",
    title_mechagnome_lazy = "Bolts Power-Save Mode",
    title_mechagnome_balanced = "Nexus Protocol 7",

    title_frostwolf_default = "Snowpaw",
    title_frostwolf_greedy = "Ravenous Frostwolf",
    title_frostwolf_picky = "Fussy Frostwolf",
    title_frostwolf_warrior = "Frostwolf Warrior",
    title_frostwolf_clingy = "Loyal Frostwolf",
    title_frostwolf_hypochondriac = "Anxious Frostwolf",
    title_frostwolf_lazy = "Lazy Frostwolf",
    title_frostwolf_balanced = "Steadfast Frostwolf",

    title_quilboar_default = "Spike",
    title_quilboar_greedy = "Ravenous Quilboar",
    title_quilboar_picky = "Fussy Quilboar",
    title_quilboar_warrior = "Stubborn Quilboar",
    title_quilboar_clingy = "Clingy Quilboar",
    title_quilboar_hypochondriac = "Anxious Quilboar",
    title_quilboar_lazy = "Lazy Quilboar",
    title_quilboar_balanced = "Balanced Quilboar",

    box_sounds       = "Sound",
    box_visual       = "Visuals",
    box_guide        = "Guide",
    box_stall        = "Stable",
    sound_enabled    = "Sound enabled",
    sound_interact   = "Interaction sound",
    sound_evolve     = "Evolution sound",
    sound_comment    = "Comment sound",
    lbl_show_bubbles = "Show speech bubbles",
    lbl_show_emotes  = "Show emotes",
    btn_reset        = "Reset",

    guide_1 = "Start the game and choose one of 6 pets.",
    guide_2 = "Care for 5 needs: hunger, happiness, energy, health, hygiene.",
    guide_3 = "Use 6 interactions — each has a cooldown.",
    guide_4 = "Gain XP from interactions (high happiness = more XP).",
    guide_5 = "Evolve at 200 XP (youth) and 600 XP (adult).",
    guide_6 = "Your play style shapes your pet's personality.",
    guide_7 = "Use the stable to switch between pets or adopt new ones.",
    guide_8 = "Adult pets can be retired and stay in the stable.",
})
