-- German Hangman puzzle answers and clues.
local W = ArcadiaNexus.HGM_Words
if not W then return end

W:RegisterLocale("deDE", {
    ARTHAS = { word="ARTHAS", hint="Der Lichkönig, einstiger Prinz von Lordaeron." },
    SYLVANAS = { word="SYLVANAS", hint="Bansheekönigin der Untoten, einstige Rangerin." },
    THRALL = { word="THRALL", hint="Grüner Kriegshäuptling, Sohn von Durotan." },
    ILLIDAN = { word="ILLIDAN", hint="Der Verratene, Jäger von Dämonen." },
    JAINA = { word="JAINA", hint="Erzmagierin von Dalaran, Tochter des Meeres." },
    ANDUIN = { word="ANDUIN", hint="König von Sturmwind, Sohn Varians." },
    BOLVAR = { word="BOLVAR", hint="Ehemaliger Regent von Sturmwind und späterer Lichkönig." },
    TYRANDE = { word="TYRANDE", hint="Hohepriesterin von Elune, Gefährtin Malfurions." },
    MALFURION = { word="MALFURION", hint="Der erste Druide, Beschützer der Natur." },
    MAGNI = { word="MAGNI", hint="Früherer König von Eisenschmiede und Sprecher Azeroths." },
    KHADGAR = { word="KHADGAR", hint="Erzmagier und Hüter des Portals in Shattrath." },
    VARIAN = { word="VARIAN", hint="Ehemaliger König von Sturmwind, auch als Lo'Gosh bekannt." },
    GARROSH = { word="GARROSH", hint="Sohn Grom Höllschreis und früherer Kriegshäuptling der Horde." },
    GULDAN = { word="GUL'DAN", hint="Orcischer Hexenmeister, Verräter seines Volkes." },
    MEDIVH = { word="MEDIVH", hint="Der letzte Hüter, öffnete das Dunkle Portal." },
    DEATHWING = { word="TODESSCHWINGE", hint="Der Weltenbrecher, einst Neltharion." },
    ALEXSTRASZA = { word="ALEXSTRASZA", hint="Drachenkönigin und Lebensbinderin." },
    YSERA = { word="YSERA", hint="Aspekt des grünen Drachenschwarms, Hüterin des Traums." },
    NOZDORMU = { word="NOZDORMU", hint="Aspekt der Zeit, Hüter der Ewigkeit." },
    KALECGOS = { word="KALECGOS", hint="Aspekt der Magie, blauer Drachenschwarm." },
    XAVIUS = { word="XAVIUS", hint="Der Albtraumtyrann, einst ein Berater Azsharis." },
    AZSHARA = { word="AZSHARA", hint="Einst Königin der Kaldorei, später Herrscherin der Naga." },
    SARGERAS = { word="SARGERAS", hint="Gefallener Titan und Herrscher der Brennenden Legion." },
    ARCHIMONDE = { word="ARCHIMONDE", hint="Mächtiger Eredar und Feldherr der Brennenden Legion." },
    KILJAEDEN = { word="KIL'JAEDEN", hint="Der Betrüger, einer der mächtigsten Eredar der Legion." },
    CENARIUS = { word="CENARIUS", hint="Halbgott des Waldes, Sohn Malorne und Elunes." },
    RAGNAROS = { word="RAGNAROS", hint="Feuerfürst im Geschmolzenen Kern." },
    NEFARIAN = { word="NEFARIAN", hint="Sohn Todesschwinges und Herrscher des Pechschwingenhortes." },
    CTHUN = { word="C'THUN", hint="Alter Gott, schlummert unter Ahn'Qiraj." },
    YOGGSARON = { word="YOGG-SARON", hint="Alter Gott des Wahnsinns, gefangen in Ulduar." },
    STORMWIND = { word="STURMWIND", hint="Die größte menschliche Stadt auf Azeroth." },
    ORGRIMMAR = { word="ORGRIMMAR", hint="Hauptstadt der Horde, benannt nach Orgrim Doomhammer." },
    DALARAN = { word="DALARAN", hint="Fliegende Magierstadt, Heimat der Kirin Tor." },
    IRONFORGE = { word="EISENSCHMIEDE", hint="Zwergenfestung tief im Berg Khaz Modan." },
    DARNASSUS = { word="DARNASSUS", hint="Einst Hauptstadt der Nachtelfen auf dem Weltenbaum." },
    UNDERCITY = { word="UNTERSTADT", hint="Gruftstadt unter Lordaerons Ruinen, Heimat der Untoten." },
    THUNDERBLUFF = { word="DONNERFELS", hint="Tauren-Hauptstadt auf mächtigen Klippen in Mulgore." },
    SILVERMOON = { word="SILBERMOND", hint="Hauptstadt der Blutelfen in Quel'Thalas." },
    EXODAR = { word="EXODAR", hint="Raumschiff der Draenei, abgestürzt auf der Azurmythosinsel." },
    ICECROWN = { word="EISKRONE", hint="Eisige Region im Norden Nordends, einst Sitz des Lichkönigs." },
    BLACKROCK = { word="SCHWARZFELS", hint="Vulkanischer Berg zwischen der Brennenden Steppe und der Sengenden Schlucht." },
    STRATHOLME = { word="STRATHOLME", hint="Stadt, die Arthas im Dritten Krieg niederbrannte." },
    LORDAERON = { word="LORDAERON", hint="Menschenkönigreich, das dem Seuchenplag zum Opfer fiel." },
    OUTLAND = { word="SCHERBENWELT", hint="Überbleibsel der explodierten Welt Draenor." },
    NORTHREND = { word="NORDEND", hint="Frostiger Kontinent im Norden, Heimat des Lichkönigs." },
    PANDARIA = { word="PANDARIA", hint="Verborgener Kontinent, Heimat der Pandaren." },
    ZANDALAR = { word="ZANDALAR", hint="Trollinsel, Stammland der Zandalari." },
    FROSTMOURNE = { word="FROSTGRAM", hint="Das Schwert des Lichkönigs, das Seelen verschlingt." },
    ASHBRINGER = { word="ASCHENBRINGER", hint="Das heilige Schwert des Lichts, Waffe der Paladine." },
    THUNDERFURY = { word="DONNERZORN", hint="Gesegnetes Schwert des Windsuchers." },
    SHADOWMOURNE = { word="SCHATTENGRAM", hint="Legendäre Axt, geschmiedet aus Splittern des Frostthrons." },
    SULFURAS = { word="SULFURAS", hint="Hand von Ragnaros, der feurige Hammer." },
    VALANYR = { word="VAL'ANYR", hint="Hammer der alten Könige, aus Titanenerz." },
    DOOMHAMMER = { word="SCHICKSALSHAMMER", hint="Der Schicksalshammer, Thralls Kriegswaffe." },
    TAESHALACH = { word="TAESHALACH", hint="Titanenklinge von Aggramar." },
    ATIESH = { word="ATIESH", hint="Stab von Medivh, dem letzten Hüter." },
    XALATATH = { word="XAL'ATATH", hint="Messer des Schwarzen Imperiums." },
    THORIIDAL = { word="THORI'DAL", hint="Legendärer Bogen, bekannt als Furor der Sterne." },
    SHALAMAYNE = { word="SHALAMAYNE", hint="Schwert von Varian Wrynn, dem Sohn Llanes." },
    MOLTENCORE = { word="GESCHMOLZENER KERN", hint="Vulkanischer Schlachtzug tief im Schwarzfels, in dem Ragnaros wartet." },
    KARAZHAN = { word="KARAZHAN", hint="Medivhs verwunschener Turm im Gebirgspass der Totenwinde." },
    NAXXRAMAS = { word="NAXXRAMAS", hint="Schwimmende Nekropole, Bastion des Lich Kel'Thuzad." },
    ULDUAR = { word="ULDUAR", hint="Titanenfestung, Gefängnis von Yogg-Saron." },
    ICECROWNCITADEL = { word="EISKRONENZITADELLE", hint="Festung des Lichkönigs und Höhepunkt des Kampfes in Nordend." },
    SUNWELLPLATEAU = { word="SONNENBRUNNENPLATEAU", hint="Schlachtzug auf der Insel von Quel'Danas, in dem Kil'jaeden erscheint." },
    BLACKTEMPLE = { word="SCHWARZER TEMPEL", hint="Illidans Festung im Schattenmondtal der Scherbenwelt." },
    AHNQIRAJ = { word="AHN'QIRAJ", hint="Altertümlicher Schlachtzug und Gefängnis von C'Thun." },
    PALADIN = { word="PALADIN", hint="Heiliger Krieger des Lichts, Beschützer der Unschuldigen." },
    DRUID = { word="DRUIDE", hint="Formwandler der Natur, Diener Cenarius." },
    SHAMAN = { word="SCHAMANE", hint="Rufer der Elemente, Brückenbauer zwischen Welten." },
    WARLOCK = { word="HEXENMEISTER", hint="Dämonenbeschwörer, meistert verbotene Magie." },
    DEATHKNIGHT = { word="TODESRITTER", hint="Einstiger Held, vom Lichkönig korrumpiert." },
    ROGUE = { word="SCHURKE", hint="Meister des Schattens, Dieb und Attentäter." },
    HUNTER = { word="JAEGER", hint="Bezähmer wilder Tiere, Jäger in der Wildnis." },
    MAGE = { word="MAGIER", hint="Meister der arkanen Magie und Elementarzauber." },
    PRIEST = { word="PRIESTER", hint="Diener des Lichts oder der Schatten." },
    WARRIOR = { word="KRIEGER", hint="Meister der Waffen, Frontkämpfer ohne Magie." },
    MONK = { word="MOENCH", hint="Beweglicher Kämpfer, der Körper und Geist in Einklang bringt." },
    DEMONHUNTER = { word="DAEMONENJAEGER", hint="Jäger der Legion, der dämonische Macht gegen Dämonen einsetzt." },
    EVOKER = { word="RUFER", hint="Drachkin, der die Magie der Drachenschwärme verbindet." },
    WORGEN = { word="WORGEN", hint="Verfluchte Menschenwesen aus Gilneas, halb Wolf." },
    GOBLIN = { word="GOBLIN", hint="Erfinderisches Volk, immer auf der Suche nach Profit." },
    PANDAREN = { word="PANDAREN", hint="Volk aus Pandaria, bekannt für Braukunst und Kampfkunst." },
    DRAENEI = { word="DRAENEI", hint="Eredar, die dem Einfluss Sargeras widerstanden." },

    BAINE = { word="BAINE", hint="Hochhäuptling der Tauren und Sohn Cairnes." },
    VELEN = { word="VELEN", hint="Prophet der Draenei und Anführer der Exodar." },
    VOLJIN = { word="VOL'JIN", hint="Schattenjäger der Dunkelspeere und früherer Kriegshäuptling." },
    MURADIN = { word="MURADIN", hint="Zwergenprinz und einstiger Lehrer von Arthas." },
    REXXAR = { word="REXXAR", hint="Halboger und berühmter Champion der Horde." },
    UTHER = { word="UTHER", hint="Paladin des Lichts und Lehrer von Arthas." },
    TIRION = { word="TIRION", hint="Träger des Aschenbringers beim Sturm auf Eiskrone." },
    GREYMANE = { word="GENN GRAUMAEHNE", hint="König von Gilneas und Anführer der Worgen." },
    TURALYON = { word="TURALYON", hint="Hochgeneral der Allianz und Gemahl Allerias." },
    ALLERIA = { word="ALLERIA", hint="Windläuferin, die sich die Macht der Leere aneignete." },
    LORTHEMAR = { word="LOR'THEMAR", hint="Regent von Quel'Thalas und Anführer der Blutelfen." },
    GALLYWIX = { word="GALLYWIX", hint="Ehemaliger Handelsprinz des Bilgewasserkartells." },
    MATHIAS = { word="MATHIAS SHAW", hint="Meisterspion und Leiter von SI:7." },
    MAIEV = { word="MAIEV", hint="Nachtelfische Wächterin, die Illidan jagte." },
    AKAMA = { word="AKAMA", hint="Gebrochener Weiser und Gegner Illidans im Schwarzen Tempel." },
    KAELTHAS = { word="KAEL'THAS", hint="Blutelfenprinz, der nach magischer Macht strebte." },
    VASHJ = { word="LADY VASHJ", hint="Naga-Hexe und treue Dienerin Illidans." },
    NATHANOS = { word="NATHANOS", hint="Dunkler Waldläufer und Champion von Sylvanas." },
    ORWEYNA = { word="ORWEYNA", hint="Junge Haranir und Wächterin der Wurzelpfade." },
    MAYLA = { word="MAYLA", hint="Hochhäuptling der Hochbergtauren." },
    THALYSSRA = { word="THALYSSRA", hint="Erste Arkanistin und Anführerin der Nachtgeborenen." },

    SHATTRATH = { word="SHATTRATH", hint="Zuflucht in der Scherbenwelt und Sitz der Sha'tar." },
    SURAMAR = { word="SURAMAR", hint="Uralte, von einer magischen Kuppel geschützte Elfenstadt." },
    GILNEAS = { word="GILNEAS", hint="Abgeschottetes Menschenkönigreich hinter dem Graumähnenwall." },
    KEZAN = { word="KEZAN", hint="Goblininsel und Heimat von Lorenhall." },
    TANARIS = { word="TANARIS", hint="Wüstengebiet mit Gadgetzan und den Höhlen der Zeit." },
    BORALUS = { word="BORALUS", hint="Hafenhauptstadt von Kul Tiras." },
    KULTIRAS = { word="KUL TIRAS", hint="Seefahrernation und Heimat von Jaina Prachtmeer." },
    DAZARALOR = { word="DAZAR'ALOR", hint="Goldene Hauptstadt der Zandalari." },
    REVENDRETH = { word="REVENDRETH", hint="Reich der Sühne und Heimat der Venthyr." },
    BASTION = { word="BASTION", hint="Leuchtendes Reich der Kyrianer." },
    MALDRAXXUS = { word="MALDRAXXUS", hint="Militärisches Reich der Nekrolords." },
    ARDENWEALD = { word="ARDENWALD", hint="Waldreich der Nachtfae und Ort der Wiedergeburt." },
    DRAGONISLES = { word="DRACHENINSELN", hint="Uralte Heimat der fünf Drachenschwärme." },
    BROKENISLES = { word="VERHEERTE INSELN", hint="Inselgruppe mit Suramar und dem Grabmal des Sargeras." },
    SHADOWLANDS = { word="SCHATTENLANDE", hint="Jenseitswelt, in die sterbliche Seelen reisen." },
    DRAGONBLIGHT = { word="DRACHENOEDE", hint="Verschneite Region Nordends mit dem Wyrmruhtempel." },
    TELDRASSIL = { word="TELDRASSIL", hint="Ehemaliger Weltenbaum und Heimat der Nachtelfen." },

    GOREHOWL = { word="BLUTSCHREI", hint="Berühmte Axt von Grom Höllschrei." },
    GORSHALACH = { word="GORSHALACH", hint="Gewaltiges Schwert des gefallenen Titanen Sargeras." },
    ASHKANDI = { word="ASHKANDI", hint="Großschwert aus dem Pechschwingenhort." },
    SHADOWFANG = { word="SCHATTENFANG", hint="Seltene Klinge aus Burg Schattenfang." },
    SCYTHEOFELUNE = { word="SENSE VON ELUNE", hint="Artefakt, das mit dem Ursprung der Worgen verbunden ist." },
    FEARBREAKER = { word="FURCHTBRECHER", hint="Zwergenhammer, den Anduin von Magni erhielt." },
    DRAGONWRATH = { word="DRACHENZORN", hint="Legendärer Stab und Vermächtnis von Tarecgosa." },
    QUELDELAR = { word="QUEL'DELAR", hint="Die Schwesterklinge und Schwert von Quel'Thalas." },
    APOCALYPSE = { word="APOKALYPSE", hint="Runenklinge der unheiligen Todesritter." },
    WARGLAIVES = { word="KRIEGSGLAIVEN VON AZZINOTH", hint="Zwillingswaffen des Verräters Illidan." },
    KINGSMOURNE = { word="KOENIGSGRAM", hint="Runenklinge, zu der Shalamayne umgeschmiedet wurde." },
    HAMMEROFNAARU = { word="HAMMER DER NAARU", hint="Kristalline Zweihandwaffe aus Gruuls Unterschlupf." },
    FANGSOFTHEFATHER = { word="FAENGE DES VATERS", hint="Legendäre Dolche für Schurken aus Todesschwinges Vermächtnis." },

    FIRELANDS = { word="FEUERLANDE", hint="Elementare Domäne von Ragnaros." },
    NIGHTHOLD = { word="NACHTFESTE", hint="Palastschlachtzug im Herzen von Suramar." },
    ANTORUS = { word="ANTORUS", hint="Brennender Thron und Machtzentrum der Legion." },
    NYALOTHA = { word="NY'ALOTHA", hint="Erwachende Stadt des Alten Gottes N'Zoth." },
    BLACKWINGLAIR = { word="PECHSCHWINGENHORT", hint="Nefarians Versteck auf dem Schwarzfels." },
    TEMPESTKEEP = { word="FESTUNG DER STUERME", hint="Naaru-Festung unter der Kontrolle von Kael'thas." },
    DRAGONSOUL = { word="DRACHENSEELE", hint="Schlachtzug gegen Todesschwinges letzten Angriff." },
    CASTLENATHRIA = { word="SCHLOSS NATHRIA", hint="Sitz von Graf Denathrius in Revendreth." },
    MOUNTHYJAL = { word="SCHLACHT UM DEN HYJAL", hint="Zeitreise zum Kampf gegen Archimondes Invasion." },
    SERPENTSHRINE = { word="HOEHLE DES SCHLANGENSCHREINS", hint="Unterirdischer Naga-Schlachtzug unter den Zangarmarschen." },
    TRIALOFTHECRUSADER = { word="PRUEFUNG DES KREUZFAHRERS", hint="Turnierschlachtzug des Argentumkreuzzugs in Nordend." },
    SIEGEORGRIMMAR = { word="SCHLACHT UM ORGRIMMAR", hint="Angriff auf Garroshs befestigte Hauptstadt." },

    DEADMINES = { word="TODESMINEN", hint="Von der Defiasbruderschaft besetzte Mine in Westfall." },
    STOCKADE = { word="DAS VERLIES", hint="Gefängnis tief unter Sturmwind." },
    ULDAMAN = { word="ULDAMAN", hint="Titanische Ausgrabungsstätte im Ödland." },
    MARADON = { word="MARAUDON", hint="Heilige Höhlen der Zentauren in Desolace." },
    MECHAGON = { word="MECHAGON", hint="Mechanische Stadt von König Mechagon." },
    GRIMBATOL = { word="GRIM BATOL", hint="Verfluchte Zwergenfestung im Schattenhochland." },
    SHADOWFANGKEEP = { word="BURG SCHATTENFANG", hint="Heimgesuchte Burg über dem Silberwald." },
    SCARLETMONASTERY = { word="SCHARLACHROTES KLOSTER", hint="Festung fanatischer Kreuzfahrer in Tirisfal." },
    DIREMAUL = { word="DUESTERBRUCH", hint="Zerfallene Hochgeborenenstadt in Feralas." },
    MAGISTERSTERRACE = { word="TERRASSE DER MAGISTER", hint="Kael'thas' Zuflucht auf der Insel von Quel'Danas." },
    THEOCULUS = { word="DAS OCULUS", hint="Fliegendes arkanes Gefängnis über dem Kaltarra." },
    FREEHOLD = { word="FREIHAFEN", hint="Piratenstadt an der Küste von Tiragarde." },
    NECROTICWAKE = { word="NEKROTISCHE SCHNEISE", hint="Fliegende Nekropole über Bastion." },
    WAILINGCAVERNS = { word="HOEHLEN DES WEHKLAGENS", hint="Verwunschene Höhlen im Nördlichen Brachland." },
    RAZORFENDOWNS = { word="HUEGEL DER KLINGENHAUER", hint="Von Untoten heimgesuchte Heimat der Stacheleber." },
    BLACKROCKDEPTHS = { word="SCHWARZFELSTIEFEN", hint="Gewaltige Dunkeleisenstadt im Schwarzfels." },
    AUCHENAICRYPTS = { word="AUCHENAIKRYPTA", hint="Heilige Grabstätte der Draenei in Auchindoun." },
    VIOLETHOLD = { word="VIOLETTE FESTUNG", hint="Magisches Gefängnis innerhalb Dalarans." },
    WAYCRESTMANOR = { word="KRONSTEIGANWESEN", hint="Verfluchter Adelssitz im Drustvar." },
    DAWNOFTHEINFINITE = { word="DAEMMERUNG DES EWIGEN", hint="Zeitreise gegen den Ewigen Drachenschwarm." },

    HUMANS = { word="MENSCHEN", hint="Vielseitiges Volk und Rückgrat der Allianz." },
    DWARVES = { word="ZWERGE", hint="Robuste Bewohner von Eisenschmiede und Khaz Modan." },
    GNOMES = { word="GNOME", hint="Erfinderisches Volk aus Gnomeregan." },
    ORCS = { word="ORCS", hint="Ehrenhafte Krieger, die ursprünglich aus Draenor stammen." },
    UNDEAD = { word="UNTOTE", hint="Freie Verlassene aus dem gefallenen Lordaeron." },
    TAUREN = { word="TAUREN", hint="Naturverbundenes Volk aus Mulgore." },
    TROLLS = { word="TROLLE", hint="Uraltes Volk mit zahlreichen Stämmen auf Azeroth." },
    VULPERA = { word="VULPERA", hint="Einfallsreiche Fuchsmenschen aus Vol'dun." },
    EARTHEN = { word="IRDENE", hint="Titanengeschmiedetes Volk aus Khaz Algar." },
    HARANIR = { word="HARANIR", hint="Wächter der Wurzelpfade aus Harandar." },
    NIGHTELVES = { word="NACHTELFEN", hint="Kaldorei aus den Wäldern Kalimdors." },
    DRACTHYR = { word="DRACTHYR", hint="Von Neltharion erschaffene Drachkin." },
    BLOODELVES = { word="BLUTELFEN", hint="Sin'dorei aus dem Königreich Quel'Thalas." },
    VOIDELVES = { word="LEERENELFEN", hint="Ren'dorei, die den Einflüsterungen der Leere widerstehen." },
    KULTIRANS = { word="KUL TIRANER", hint="Seefahrende Menschen aus Kul Tiras." },
    MECHAGNOMES = { word="MECHAGNOME", hint="Gnome, die Fleisch und Technik vereinen." },
    NIGHTBORNE = { word="NACHTGEBORENE", hint="Shal'dorei aus der uralten Stadt Suramar." },
    LIGHTFORGED = { word="LICHTGESCHMIEDETE DRAENEI", hint="Draenei-Veteranen der Armee des Lichts." },
    DARKIRONDWARVES = { word="DUNKELEISENZWERGE", hint="Feuererprobter Zwergenklan aus dem Schwarzfels." },
    HIGHMOUNTAINTAUREN = { word="HOCHBERGTAUREN", hint="Taurenstämme von den Verheerten Inseln." },
    MAGHARORCS = { word="ORCS DER MAG'HAR", hint="Unverdorbene Orc-Klans aus Draenor." },
    ZANDALARITROLLS = { word="ZANDALARITROLLE", hint="Stolzes Trollvolk aus dem goldenen Zandalar." },

    ONYXIA = { word="ONYXIA", hint="Schwarze Drachendame, die Sturmwinds Adel unterwanderte." },
    MALYGOS = { word="MALYGOS", hint="Ehemaliger blauer Drachenaspekt der Magie." },
    GRUUL = { word="GRUUL", hint="Gronnfürst und Drachenschlächter der Scherbenwelt." },
    MAGTHERIDON = { word="MAGTHERIDON", hint="Grubenlord, der unter der Höllenfeuerzitadelle gefangen war." },
    HOGGER = { word="HOGGER", hint="Berüchtigter Gnollhäuptling aus dem Wald von Elwynn." },
    MANNOROTH = { word="MANNOROTH", hint="Grubenlord, dessen Blut die Orcs verdarb." },
    ODYN = { word="ODYN", hint="Titanenhüter und Herrscher der Hallen der Tapferkeit." },
    ARGUS = { word="ARGUS", hint="Weltenseele, die von der Legion gequält wurde." },
    DENATHRIUS = { word="DENATHRIUS", hint="Meister der Venthyr und Herr von Schloss Nathria." },
    FYRAKK = { word="FYRAKK", hint="Feuriger Inkarnierter und Bruder von Raszageth." },
    DIMENSIUS = { word="DIMENSIUS", hint="Leerengott, der K'aresh verschlang." },
    KELTHUZAD = { word="KEL'THUZAD", hint="Lich und loyaler Diener des Lichkönigs." },
    ANUBARAK = { word="ANUB'ARAK", hint="Gefallener König des nerubischen Reiches Azjol-Nerub." },
    LEOTHERAS = { word="LEOTHERAS", hint="Dämonenjäger mit gespaltener Seele im Schlangenschrein." },
    PATCHWERK = { word="FLECKENWERK", hint="Gewaltige Abscheulichkeit in Naxxramas." },
    SUPREMUS = { word="SUPREMUS", hint="Massiver Abyssal im Hof des Schwarzen Tempels." },
    MIMIRON = { word="MIMIRON", hint="Titanenhüter und genialer Erfinder in Ulduar." },
    ALGALON = { word="ALGALON", hint="Kosmischer Beobachter und Prüfer Azeroths." },
    LEISHEN = { word="LEI SHEN", hint="Wiedererweckter Donnerkönig der Mogu." },
    BLACKHAND = { word="SCHWARZFAUST", hint="Kriegsherr des Schwarzfelsklans in der Gießerei." },
    KROSUS = { word="KROSUS", hint="Gewaltiger Verdammnislord vor der Nachtfestung." },
    RAZAGETH = { word="RASZAGETH", hint="Sturmincarnierte und Gegnerin der Drachenaspekte." },
    ANSUREK = { word="ANSUREK", hint="Nerubische Königin des Reiches Azj-Kahet." },
    CHOGALL = { word="CHO'GALL", hint="Oger-Magier und Anführer des Schattenhammerklans." },
    IMPERATORMARGOK = { word="KAISER MAR'GOK", hint="Herrscher des Hochfelsimperiums der Oger." },
    KAZZAK = { word="LORD KAZZAK", hint="Verdammnislord und Kommandant der Brennenden Legion." },
    BRUTALLUS = { word="BRUTALLUS", hint="Mächtiger Grubenlord am Sonnenbrunnen." },
    NZOTH = { word="N'ZOTH", hint="Alter Gott hinter vielen Verderbnissen Azeroths." },
    RYGELON = { word="RYGELON", hint="Verderbter Konstellar im Mausoleum der Ersten." },
    JAILER = { word="DER KERKERMEISTER", hint="Zovaal, verbannter Ewiger der Schattenlande." },
    KILROGG = { word="KILROGG TOTAUGE", hint="Kriegsherr des Klans des Blutenden Auges." },
    ZAQUL = { word="ZA'QUL", hint="Herold N'Zoths im Ewigen Palast." },
    THELICHKING = { word="DER LICHKOENIG", hint="Herrscher der Geißel auf dem Frostthron." },
    THOK = { word="THOK DER BLUTDUERSTIGE", hint="Riesiger Teufelssaurier in Garroshs Gefangenschaft." },
    URSOC = { word="URSOC", hint="Uralter Bärengott und Beschützer der Wildnis." },

    ALLIANCE = { word="ALLIANZ", hint="Fraktion um Sturmwind, Eisenschmiede und ihre Verbündeten." },
    HORDE = { word="HORDE", hint="Fraktion, die in Orgrimmar ihren wichtigsten Sitz hat." },
    KIRINTOR = { word="KIRIN TOR", hint="Magierorden, der über Dalaran wacht." },
    ILLIDARI = { word="ILLIDARI", hint="Dämonenjäger und Anhänger Illidans." },
    ARGENTDAWN = { word="ARGENTUMDAEMMERUNG", hint="Orden im Kampf gegen die untote Geißel." },
    EARTHENRING = { word="IRDENER RING", hint="Schamanischer Bund zum Schutz der Elemente." },
    SILVERHAND = { word="SILBERNE HAND", hint="Von Uther gegründeter Paladinorden." },
    EBONBLADE = { word="RITTER DER SCHWARZEN KLINGE", hint="Orden unabhängiger Todesritter." },
    CENARIONCIRCLE = { word="ZIRKEL DES CENARIUS", hint="Druidenbund zum Schutz der Natur." },
    BILGEWATERCARTEL = { word="BILGEWASSERKARTELL", hint="Goblinkartell unter Gazlowes Führung." },
    STEAMWHEEDLE = { word="DAMPFDRUCKKARTELL", hint="Neutrales Goblinkartell mit Städten in Kalimdor." },
    WARDENS = { word="WAECHTERINNEN", hint="Nachtelfischer Orden von Jägerinnen und Kerkermeisterinnen." },
    VALARJAR = { word="VALARJAR", hint="Von Odyn erwählte Vrykulkrieger." },
    BURNINGLEGION = { word="BRENNENDE LEGION", hint="Dämonische Armee des gefallenen Titanen Sargeras." },
    TWILIGHTSHAMMER = { word="SCHATTENHAMMERKLAN", hint="Kult, der den Alten Göttern dient." },
    SCARLETCRUSADE = { word="SCHARLACHROTER KREUZZUG", hint="Fanatischer Orden im Kampf gegen Untote." },
    DRAGONASPECTS = { word="DRACHENASPEKTE", hint="Von den Titanen ermächtigte Wächter Azeroths." },
    SHATTEREDSUN = { word="OFFENSIVE DER ZERSCHMETTERTEN SONNE", hint="Bündnis gegen Kil'jaedens Kräfte auf Quel'Danas." },
    BLACKDRAGONFLIGHT = { word="SCHWARZER DRACHENSCHWARM", hint="Drachenschwarm des Erdwächters Neltharion." },
    EXPLORERSLEAGUE = { word="FORSCHERLIGA", hint="Zwergische Vereinigung für Geschichte und Archäologie." },

    MURLOC = { word="MURLOC", hint="Amphibischer Küstenbewohner mit unverkennbarem Ruf." },
    KOBOLD = { word="KOBOLD", hint="Kerzenliebender Höhlenbewohner." },
    GNOLL = { word="GNOLL", hint="Hyänenartiger Humanoider aus Rudeln." },
    HARPY = { word="HARPYIE", hint="Geflügelte Plünderin aus Kalimdors Bergen." },
    QUILBOAR = { word="STACHELEBER", hint="Stacheliges Volk aus dem Brachland." },
    OGRE = { word="OGER", hint="Großer Humanoider mit Wurzeln auf Draenor." },
    DRAGON = { word="DRACHE", hint="Mächtiges Wesen eines der Drachenschwärme." },
    BASILISK = { word="BASILISK", hint="Reptil, dessen Blick seine Beute versteinern kann." },
    NERUBIAN = { word="NERUBER", hint="Spinnenartiges Volk aus den Tiefen Azeroths." },
    MAGNATAUR = { word="MAGNATAUR", hint="Riesiger Verwandter der Zentauren aus Nordend." },
    GRONN = { word="GRONN", hint="Gigantischer Herrscher der Oger von Draenor." },
    NAGA = { word="NAGA", hint="Vom Meer verwandelte ehemalige Hochgeborene." },
    TOLVIR = { word="TOL'VIR", hint="Katzenartige Titanenkonstrukte aus Uldum." },
    ELEMENTAL = { word="ELEMENTAR", hint="Verkörperung von Feuer, Wasser, Erde oder Luft." },
    DREADLORD = { word="SCHRECKENSLORD", hint="Manipulativer Nathrezim aus den Schattenlanden." },

    MINING = { word="BERGBAU", hint="Sammelt Erze und Steine aus Vorkommen." },
    HERBALISM = { word="KRAEUTERKUNDE", hint="Sammelt Pflanzen für Tränke und Handwerk." },
    SKINNING = { word="KUERSCHNEREI", hint="Gewinnt Leder von erlegten Wildtieren." },
    COOKING = { word="KOCHKUNST", hint="Bereitet stärkende Speisen zu." },
    FISHING = { word="ANGELN", hint="Fängt Fische in Azeroths Gewässern." },
    ALCHEMY = { word="ALCHEMIE", hint="Braut Tränke, Elixiere und Transmutationen." },
    BLACKSMITHING = { word="SCHMIEDEKUNST", hint="Fertigt Metallwaffen und schwere Rüstung." },
    ENCHANTING = { word="VERZAUBERKUNST", hint="Verstärkt Ausrüstung mit magischen Effekten." },
    ENGINEERING = { word="INGENIEURSKUNST", hint="Baut Geräte, Sprengstoff und mechanische Helfer." },
    INSCRIPTION = { word="INSCHRIFTENKUNDE", hint="Erschafft Glyphen, Verträge und magische Schriften." },
    LEATHERWORKING = { word="LEDERVERARBEITUNG", hint="Fertigt Leder- und Kettenrüstung." },
    TAILORING = { word="SCHNEIDEREI", hint="Verarbeitet Stoff zu Kleidung und Taschen." },
    JEWELCRAFTING = { word="JUWELIERSKUNST", hint="Schleift Edelsteine und fertigt Schmuck." },
    ARCHAEOLOGY = { word="ARCHAEOLOGIE", hint="Untersucht Fragmente vergangener Kulturen." },
    FIRSTAID = { word="ERSTE HILFE", hint="Ehemaliger Nebenberuf zum Herstellen von Verbänden." },
})
