-- English Hangman puzzle answers and clues.
local W = ArcadiaNexus.HGM_Words
if not W then return end

W:RegisterLocale("enUS", {
    ARTHAS = { word="ARTHAS", hint="The Lich King, once Prince of Lordaeron." },
    SYLVANAS = { word="SYLVANAS", hint="Banshee Queen of the Forsaken, former ranger." },
    THRALL = { word="THRALL", hint="Great Warchief, son of Durotan." },
    ILLIDAN = { word="ILLIDAN", hint="The Betrayer, hunter of demons." },
    JAINA = { word="JAINA", hint="Archmage of Dalaran, daughter of the sea." },
    ANDUIN = { word="ANDUIN", hint="King of Stormwind, son of Varian." },
    BOLVAR = { word="BOLVAR", hint="Former Regent of Stormwind who later became the Lich King." },
    TYRANDE = { word="TYRANDE", hint="High Priestess of Elune, companion of Malfurion." },
    MALFURION = { word="MALFURION", hint="The first druid, protector of nature." },
    MAGNI = { word="MAGNI", hint="Former King of Ironforge and Speaker for Azeroth." },
    KHADGAR = { word="KHADGAR", hint="Archmage and keeper of the portal in Shattrath." },
    VARIAN = { word="VARIAN", hint="King of Stormwind, Lo'Gosh the Wolf Ancient." },
    GARROSH = { word="GARROSH", hint="Son of Grom Hellscream, former Warchief of the Horde." },
    GULDAN = { word="GUL'DAN", hint="Orcish warlock, traitor to his people." },
    MEDIVH = { word="MEDIVH", hint="The Last Guardian, who opened the Dark Portal." },
    DEATHWING = { word="DEATHWING", hint="The Worldbreaker, once known as Neltharion." },
    ALEXSTRASZA = { word="ALEXSTRASZA", hint="Dragon Queen, life-binder and protector." },
    YSERA = { word="YSERA", hint="Aspect of the Green Dragonflight, guardian of the Dream." },
    NOZDORMU = { word="NOZDORMU", hint="Aspect of Time, keeper of eternity." },
    KALECGOS = { word="KALECGOS", hint="Aspect of Magic, blue dragonflight." },
    XAVIUS = { word="XAVIUS", hint="The Nightmare Lord, once an advisor to Azshara." },
    AZSHARA = { word="AZSHARA", hint="Once Queen of the Kaldorei, now Naga Empress." },
    SARGERAS = { word="SARGERAS", hint="Fallen Titan, master of the Burning Legion." },
    ARCHIMONDE = { word="ARCHIMONDE", hint="One of the Eredar Lords of the Burning Legion." },
    KILJAEDEN = { word="KIL'JAEDEN", hint="The Deceiver, one of the Legion's most powerful Eredar." },
    CENARIUS = { word="CENARIUS", hint="Demigod of the forest, son of Malorne and Elune." },
    RAGNAROS = { word="RAGNAROS", hint="Firelord, master of Molten Core." },
    NEFARIAN = { word="NEFARIAN", hint="Son of Deathwing, master of Blackwing Lair." },
    CTHUN = { word="C'THUN", hint="Old God, slumbering beneath Ahn'Qiraj." },
    YOGGSARON = { word="YOGG-SARON", hint="Old God of madness, imprisoned in Ulduar." },
    STORMWIND = { word="STORMWIND", hint="The greatest human city on Azeroth." },
    ORGRIMMAR = { word="ORGRIMMAR", hint="Horde capital, named after Orgrim Doomhammer." },
    DALARAN = { word="DALARAN", hint="Flying city of mages, home of the Kirin Tor." },
    IRONFORGE = { word="IRONFORGE", hint="Dwarven fortress deep in Khaz Modan." },
    DARNASSUS = { word="DARNASSUS", hint="Once capital of the night elves atop the World Tree." },
    UNDERCITY = { word="UNDERCITY", hint="Crypt-city beneath the ruins of Lordaeron, home of the Forsaken." },
    THUNDERBLUFF = { word="THUNDER BLUFF", hint="Tauren capital on mighty bluffs in Mulgore." },
    SILVERMOON = { word="SILVERMOON", hint="Blood elf capital in Quel'Thalas." },
    EXODAR = { word="EXODAR", hint="Draenei spaceship that crashed on the Azuremyst Isles." },
    ICECROWN = { word="ICECROWN", hint="Frozen region in northern Northrend, once ruled by the Lich King." },
    BLACKROCK = { word="BLACKROCK", hint="Volcanic mountain, home of dragons and orcs." },
    STRATHOLME = { word="STRATHOLME", hint="City burned by Arthas during the Third War." },
    LORDAERON = { word="LORDAERON", hint="Human kingdom that fell to the Scourge plague." },
    OUTLAND = { word="OUTLAND", hint="Remnants of the shattered world of Draenor." },
    NORTHREND = { word="NORTHREND", hint="Frozen continent in the north, home of the Lich King." },
    PANDARIA = { word="PANDARIA", hint="Hidden continent, home of the Pandaren." },
    ZANDALAR = { word="ZANDALAR", hint="Troll island, homeland of the Zandalari." },
    FROSTMOURNE = { word="FROSTMOURNE", hint="The Lich King's sword that devours souls." },
    ASHBRINGER = { word="ASHBRINGER", hint="Holy sword of the Light, weapon of the Silver Hand." },
    THUNDERFURY = { word="THUNDERFURY", hint="Blessed Blade of the Windseeker." },
    SHADOWMOURNE = { word="SHADOWMOURNE", hint="Legendary axe forged with fragments of the Frozen Throne." },
    SULFURAS = { word="SULFURAS", hint="Hand of Ragnaros, the fiery hammer." },
    VALANYR = { word="VAL'ANYR", hint="Hammer of Ancient Kings, forged from titan ore." },
    DOOMHAMMER = { word="DOOMHAMMER", hint="The destiny hammer, Thrall's weapon of war." },
    TAESHALACH = { word="TAESHALACH", hint="Titan blade of Aggramar." },
    ATIESH = { word="ATIESH", hint="Staff of Medivh, the Last Guardian." },
    XALATATH = { word="XAL'ATATH", hint="Knife of the Black Empire." },
    THORIIDAL = { word="THORI'DAL", hint="Legendary bow known as the Stars' Fury." },
    SHALAMAYNE = { word="SHALAMAYNE", hint="Sword of Varian Wrynn, son of Llane." },
    MOLTENCORE = { word="MOLTEN CORE", hint="Volcanic raid beneath Blackrock Mountain, Ragnaros awaits." },
    KARAZHAN = { word="KARAZHAN", hint="Tower of Medivh, first raid in Burning Crusade." },
    NAXXRAMAS = { word="NAXXRAMAS", hint="Floating necropolis, bastion of the lich Kel'Thuzad." },
    ULDUAR = { word="ULDUAR", hint="Titan fortress, prison of Yogg-Saron." },
    ICECROWNCITADEL = { word="ICECROWN CITADEL", hint="Stronghold of the Lich King and climax of the war in Northrend." },
    SUNWELLPLATEAU = { word="SUNWELL PLATEAU", hint="Raid on the Isle of Quel'Danas where Kil'jaeden emerges." },
    BLACKTEMPLE = { word="BLACK TEMPLE", hint="Illidan's fortress in Shadowmoon Valley, Outland." },
    AHNQIRAJ = { word="AHN'QIRAJ", hint="Ancient raid, prison of C'Thun." },
    PALADIN = { word="PALADIN", hint="Holy warrior of the Light, protector of the innocent." },
    DRUID = { word="DRUID", hint="Shapeshifter of nature, servant of Cenarius." },
    SHAMAN = { word="SHAMAN", hint="Caller of elements, bridge between worlds." },
    WARLOCK = { word="WARLOCK", hint="Demon summoner, master of forbidden magic." },
    DEATHKNIGHT = { word="DEATH KNIGHT", hint="Former hero, corrupted by the Lich King." },
    ROGUE = { word="ROGUE", hint="Master of shadows, thief and assassin." },
    HUNTER = { word="HUNTER", hint="Tamer of wild beasts, tracker in the wilds." },
    MAGE = { word="MAGE", hint="Master of arcane magic and elemental spells." },
    PRIEST = { word="PRIEST", hint="Servant of the Light or the Shadow." },
    WARRIOR = { word="WARRIOR", hint="Master of weapons, frontline fighter without magic." },
    MONK = { word="MONK", hint="Agile fighter who brings body and spirit into harmony." },
    DEMONHUNTER = { word="DEMON HUNTER", hint="Hunter of the Legion who turns demonic power against demons." },
    EVOKER = { word="EVOKER", hint="Draconic caster who combines the magic of the dragonflights." },
    WORGEN = { word="WORGEN", hint="Cursed humans from Gilneas, half wolf." },
    GOBLIN = { word="GOBLIN", hint="Inventive people always seeking profit." },
    PANDAREN = { word="PANDAREN", hint="Peaceful citizens, masters of brewing and combat." },
    DRAENEI = { word="DRAENEI", hint="Eredar who resisted the influence of Sargeras." },

    BAINE = { word="BAINE", hint="High Chieftain of the tauren and son of Cairne." },
    VELEN = { word="VELEN", hint="Prophet of the draenei and leader of the Exodar." },
    VOLJIN = { word="VOL'JIN", hint="Darkspear shadow hunter and former Warchief." },
    MURADIN = { word="MURADIN", hint="Dwarven prince who once trained Arthas." },
    REXXAR = { word="REXXAR", hint="Half-ogre and famed champion of the Horde." },
    UTHER = { word="UTHER", hint="Paladin of the Light and mentor to Arthas." },
    TIRION = { word="TIRION", hint="Wielder of Ashbringer during the assault on Icecrown." },
    GREYMANE = { word="GENN GREYMANE", hint="King of Gilneas and leader of the worgen." },
    TURALYON = { word="TURALYON", hint="High Exarch of the Alliance and husband of Alleria." },
    ALLERIA = { word="ALLERIA", hint="Windrunner who learned to wield the Void." },
    LORTHEMAR = { word="LOR'THEMAR", hint="Regent Lord of Quel'Thalas and the blood elves." },
    GALLYWIX = { word="GALLYWIX", hint="Former Trade Prince of the Bilgewater Cartel." },
    MATHIAS = { word="MATHIAS SHAW", hint="Spymaster and leader of SI:7." },
    MAIEV = { word="MAIEV", hint="Night elf warden who hunted Illidan." },
    AKAMA = { word="AKAMA", hint="Broken elder who opposed Illidan in the Black Temple." },
    KAELTHAS = { word="KAEL'THAS", hint="Blood elf prince driven by a hunger for magic." },
    VASHJ = { word="LADY VASHJ", hint="Naga sorceress and loyal servant of Illidan." },
    NATHANOS = { word="NATHANOS", hint="Dark ranger and champion of Sylvanas." },
    ORWEYNA = { word="ORWEYNA", hint="Young haranir and guardian of the rootways." },
    MAYLA = { word="MAYLA", hint="High Chieftain of the Highmountain tauren." },
    THALYSSRA = { word="THALYSSRA", hint="First Arcanist and leader of the nightborne." },

    SHATTRATH = { word="SHATTRATH", hint="Outland sanctuary and home of the Sha'tar." },
    SURAMAR = { word="SURAMAR", hint="Ancient elven city once protected by a magical dome." },
    GILNEAS = { word="GILNEAS", hint="Human kingdom sealed behind the Greymane Wall." },
    KEZAN = { word="KEZAN", hint="Goblin island and home of Undermine." },
    TANARIS = { word="TANARIS", hint="Desert containing Gadgetzan and the Caverns of Time." },
    BORALUS = { word="BORALUS", hint="Great harbor capital of Kul Tiras." },
    KULTIRAS = { word="KUL TIRAS", hint="Seafaring nation and homeland of Jaina Proudmoore." },
    DAZARALOR = { word="DAZAR'ALOR", hint="Golden capital of the Zandalari." },
    REVENDRETH = { word="REVENDRETH", hint="Realm of atonement and home of the venthyr." },
    BASTION = { word="BASTION", hint="Radiant realm of the kyrian." },
    MALDRAXXUS = { word="MALDRAXXUS", hint="Military realm of the necrolords." },
    ARDENWEALD = { word="ARDENWEALD", hint="Forest realm of the night fae and rebirth." },
    DRAGONISLES = { word="DRAGON ISLES", hint="Ancient homeland of the five dragonflights." },
    BROKENISLES = { word="BROKEN ISLES", hint="Island chain containing Suramar and the Tomb of Sargeras." },
    SHADOWLANDS = { word="SHADOWLANDS", hint="Afterlife traversed by mortal souls." },
    DRAGONBLIGHT = { word="DRAGONBLIGHT", hint="Frozen Northrend region containing Wyrmrest Temple." },
    TELDRASSIL = { word="TELDRASSIL", hint="Former World Tree and home of the night elves." },

    GOREHOWL = { word="GOREHOWL", hint="Famed axe of Grom Hellscream." },
    GORSHALACH = { word="GORSHALACH", hint="Massive sword once wielded by Sargeras." },
    ASHKANDI = { word="ASHKANDI", hint="Greatsword recovered from Blackwing Lair." },
    SHADOWFANG = { word="SHADOWFANG", hint="Rare blade found in Shadowfang Keep." },
    SCYTHEOFELUNE = { word="SCYTHE OF ELUNE", hint="Artifact tied to the origin of the worgen." },
    FEARBREAKER = { word="FEARBREAKER", hint="Dwarven mace given to Anduin by Magni." },
    DRAGONWRATH = { word="DRAGONWRATH", hint="Legendary staff and legacy of Tarecgosa." },
    QUELDELAR = { word="QUEL'DELAR", hint="The Sister Blade forged in Quel'Thalas." },
    APOCALYPSE = { word="APOCALYPSE", hint="Runeblade carried by unholy death knights." },
    WARGLAIVES = { word="WARGLAIVES OF AZZINOTH", hint="Twin weapons of Illidan the Betrayer." },
    KINGSMOURNE = { word="KINGSMOURNE", hint="Runeblade reforged from Shalamayne." },
    HAMMEROFNAARU = { word="HAMMER OF THE NAARU", hint="Crystalline weapon recovered from Gruul's Lair." },
    FANGSOFTHEFATHER = { word="FANGS OF THE FATHER", hint="Legendary rogue daggers tied to Deathwing's legacy." },

    FIRELANDS = { word="FIRELANDS", hint="Elemental domain of Ragnaros." },
    NIGHTHOLD = { word="NIGHTHOLD", hint="Palace raid in the heart of Suramar." },
    ANTORUS = { word="ANTORUS", hint="The Burning Throne and seat of Legion power." },
    NYALOTHA = { word="NY'ALOTHA", hint="Waking city of the Old God N'Zoth." },
    BLACKWINGLAIR = { word="BLACKWING LAIR", hint="Nefarian's lair atop Blackrock Mountain." },
    TEMPESTKEEP = { word="TEMPEST KEEP", hint="Naaru fortress seized by Kael'thas." },
    DRAGONSOUL = { word="DRAGON SOUL", hint="Raid against Deathwing's final assault." },
    CASTLENATHRIA = { word="CASTLE NATHRIA", hint="Seat of Sire Denathrius in Revendreth." },
    MOUNTHYJAL = { word="BATTLE FOR MOUNT HYJAL", hint="Journey back to Archimonde's invasion." },
    SERPENTSHRINE = { word="SERPENTSHRINE CAVERN", hint="Subterranean naga raid beneath Zangarmarsh." },
    TRIALOFTHECRUSADER = { word="TRIAL OF THE CRUSADER", hint="Argent tournament raid in Northrend." },
    SIEGEORGRIMMAR = { word="SIEGE OF ORGRIMMAR", hint="Assault on Garrosh's fortified capital." },

    DEADMINES = { word="DEADMINES", hint="Mine occupied by the Defias Brotherhood in Westfall." },
    STOCKADE = { word="STOCKADE", hint="Prison hidden beneath Stormwind." },
    ULDAMAN = { word="ULDAMAN", hint="Titan excavation complex in the Badlands." },
    MARADON = { word="MARAUDON", hint="Sacred centaur caverns in Desolace." },
    MECHAGON = { word="MECHAGON", hint="Mechanical city ruled by King Mechagon." },
    GRIMBATOL = { word="GRIM BATOL", hint="Cursed dwarven fortress in the Twilight Highlands." },
    SHADOWFANGKEEP = { word="SHADOWFANG KEEP", hint="Haunted castle overlooking Silverpine Forest." },
    SCARLETMONASTERY = { word="SCARLET MONASTERY", hint="Stronghold of fanatical crusaders in Tirisfal." },
    DIREMAUL = { word="DIRE MAUL", hint="Ruined Highborne city in Feralas." },
    MAGISTERSTERRACE = { word="MAGISTERS' TERRACE", hint="Kael'thas' refuge on the Isle of Quel'Danas." },
    THEOCULUS = { word="THE OCULUS", hint="Flying arcane prison above the Coldarra." },
    FREEHOLD = { word="FREEHOLD", hint="Pirate town on the coast of Tiragarde." },
    NECROTICWAKE = { word="NECROTIC WAKE", hint="Flying necropolis attacking Bastion." },
    WAILINGCAVERNS = { word="WAILING CAVERNS", hint="Corrupted caverns in the Northern Barrens." },
    RAZORFENDOWNS = { word="RAZORFEN DOWNS", hint="Undead-infested home of the quilboar." },
    BLACKROCKDEPTHS = { word="BLACKROCK DEPTHS", hint="Vast Dark Iron city beneath Blackrock Mountain." },
    AUCHENAICRYPTS = { word="AUCHENAI CRYPTS", hint="Sacred draenei burial grounds within Auchindoun." },
    VIOLETHOLD = { word="VIOLET HOLD", hint="Magical prison located inside Dalaran." },
    WAYCRESTMANOR = { word="WAYCREST MANOR", hint="Cursed noble estate in Drustvar." },
    DAWNOFTHEINFINITE = { word="DAWN OF THE INFINITE", hint="Time-bending battle against the Infinite dragonflight." },

    HUMANS = { word="HUMANS", hint="Versatile people at the heart of the Alliance." },
    DWARVES = { word="DWARVES", hint="Stout people of Ironforge and Khaz Modan." },
    GNOMES = { word="GNOMES", hint="Ingenious people from Gnomeregan." },
    ORCS = { word="ORCS", hint="Honorable warriors who originally came from Draenor." },
    UNDEAD = { word="UNDEAD", hint="Free-willed Forsaken of fallen Lordaeron." },
    TAUREN = { word="TAUREN", hint="Nature-bound people from Mulgore." },
    TROLLS = { word="TROLLS", hint="Ancient people with many tribes across Azeroth." },
    VULPERA = { word="VULPERA", hint="Resourceful fox folk from Vol'dun." },
    EARTHEN = { word="EARTHEN", hint="Titan-forged people of Khaz Algar." },
    HARANIR = { word="HARANIR", hint="Guardians of the rootways from Harandar." },
    NIGHTELVES = { word="NIGHT ELVES", hint="Kaldorei from the forests of Kalimdor." },
    DRACTHYR = { word="DRACTHYR", hint="Dragonkin created by Neltharion." },
    BLOODELVES = { word="BLOOD ELVES", hint="Sin'dorei of the kingdom of Quel'Thalas." },
    VOIDELVES = { word="VOID ELVES", hint="Ren'dorei who resist the whispers of the Void." },
    KULTIRANS = { word="KUL TIRANS", hint="Seafaring humans from Kul Tiras." },
    MECHAGNOMES = { word="MECHAGNOMES", hint="Gnomes who combine flesh and machinery." },
    NIGHTBORNE = { word="NIGHTBORNE", hint="Shal'dorei from the ancient city of Suramar." },
    LIGHTFORGED = { word="LIGHTFORGED DRAENEI", hint="Draenei veterans of the Army of the Light." },
    DARKIRONDWARVES = { word="DARK IRON DWARVES", hint="Fire-hardened dwarven clan from Blackrock Mountain." },
    HIGHMOUNTAINTAUREN = { word="HIGHMOUNTAIN TAUREN", hint="Tauren tribes of the Broken Isles." },
    MAGHARORCS = { word="MAG'HAR ORCS", hint="Uncorrupted orc clans from Draenor." },
    ZANDALARITROLLS = { word="ZANDALARI TROLLS", hint="Proud troll people from golden Zandalar." },

    ONYXIA = { word="ONYXIA", hint="Black dragon who infiltrated Stormwind's nobility." },
    MALYGOS = { word="MALYGOS", hint="Former blue Dragon Aspect of magic." },
    GRUUL = { word="GRUUL", hint="Gronn lord and dragonkiller of Outland." },
    MAGTHERIDON = { word="MAGTHERIDON", hint="Pit lord imprisoned beneath Hellfire Citadel." },
    HOGGER = { word="HOGGER", hint="Infamous gnoll chieftain from Elwynn Forest." },
    MANNOROTH = { word="MANNOROTH", hint="Pit lord whose blood corrupted the orcs." },
    ODYN = { word="ODYN", hint="Titan keeper who rules the Halls of Valor." },
    ARGUS = { word="ARGUS", hint="World-soul tortured by the Burning Legion." },
    DENATHRIUS = { word="DENATHRIUS", hint="Master of the venthyr and Castle Nathria." },
    FYRAKK = { word="FYRAKK", hint="Fiery Primal Incarnate and brother of Raszageth." },
    DIMENSIUS = { word="DIMENSIUS", hint="Void lord who consumed K'aresh." },
    KELTHUZAD = { word="KEL'THUZAD", hint="Lich and loyal servant of the Lich King." },
    ANUBARAK = { word="ANUB'ARAK", hint="Fallen king of the nerubian empire Azjol-Nerub." },
    LEOTHERAS = { word="LEOTHERAS", hint="Demon hunter with a divided soul in Serpentshrine." },
    PATCHWERK = { word="PATCHWERK", hint="Enormous abomination within Naxxramas." },
    SUPREMUS = { word="SUPREMUS", hint="Massive abyssal in the Black Temple courtyard." },
    MIMIRON = { word="MIMIRON", hint="Titan keeper and brilliant inventor in Ulduar." },
    ALGALON = { word="ALGALON", hint="Cosmic observer sent to judge Azeroth." },
    LEISHEN = { word="LEI SHEN", hint="Resurrected Thunder King of the mogu." },
    BLACKHAND = { word="BLACKHAND", hint="Warlord of the Blackrock clan in the Foundry." },
    KROSUS = { word="KROSUS", hint="Massive doom lord outside the Nighthold." },
    RAZAGETH = { word="RASZAGETH", hint="Storm Incarnate and enemy of the Dragon Aspects." },
    ANSUREK = { word="ANSUREK", hint="Nerubian queen of the kingdom of Azj-Kahet." },
    CHOGALL = { word="CHO'GALL", hint="Ogre mage and leader of the Twilight's Hammer." },
    IMPERATORMARGOK = { word="IMPERATOR MAR'GOK", hint="Ruler of the Highmaul ogre empire." },
    KAZZAK = { word="LORD KAZZAK", hint="Doom lord commander of the Burning Legion." },
    BRUTALLUS = { word="BRUTALLUS", hint="Mighty pit lord at the Sunwell." },
    NZOTH = { word="N'ZOTH", hint="Old God behind many corruptions of Azeroth." },
    RYGELON = { word="RYGELON", hint="Corrupted constellar in the Sepulcher of the First Ones." },
    JAILER = { word="THE JAILER", hint="Zovaal, banished Eternal One of the Shadowlands." },
    KILROGG = { word="KILROGG DEADEYE", hint="Warlord of the Bleeding Hollow clan." },
    ZAQUL = { word="ZA'QUL", hint="Herald of N'Zoth in the Eternal Palace." },
    THELICHKING = { word="THE LICH KING", hint="Ruler of the Scourge upon the Frozen Throne." },
    THOK = { word="THOK THE BLOODTHIRSTY", hint="Giant devilsaur held captive by Garrosh." },
    URSOC = { word="URSOC", hint="Ancient bear god and protector of the wilds." },

    ALLIANCE = { word="ALLIANCE", hint="Faction centered on Stormwind and its allies." },
    HORDE = { word="HORDE", hint="Faction whose greatest stronghold is Orgrimmar." },
    KIRINTOR = { word="KIRIN TOR", hint="Order of mages that watches over Dalaran." },
    ILLIDARI = { word="ILLIDARI", hint="Demon hunters and followers of Illidan." },
    ARGENTDAWN = { word="ARGENT DAWN", hint="Order devoted to fighting the undead Scourge." },
    EARTHENRING = { word="EARTHEN RING", hint="Shamanic union that protects the elements." },
    SILVERHAND = { word="SILVER HAND", hint="Paladin order founded by Uther." },
    EBONBLADE = { word="EBON BLADE", hint="Order of independent death knights." },
    CENARIONCIRCLE = { word="CENARION CIRCLE", hint="Druidic union dedicated to protecting nature." },
    BILGEWATERCARTEL = { word="BILGEWATER CARTEL", hint="Goblin cartel led by Gazlowe." },
    STEAMWHEEDLE = { word="STEAMWHEEDLE CARTEL", hint="Neutral goblin cartel with towns across Kalimdor." },
    WARDENS = { word="WARDENS", hint="Night elf order of hunters and jailers." },
    VALARJAR = { word="VALARJAR", hint="Vrykul warriors chosen by Odyn." },
    BURNINGLEGION = { word="BURNING LEGION", hint="Demonic army of the fallen titan Sargeras." },
    TWILIGHTSHAMMER = { word="TWILIGHT'S HAMMER", hint="Cult devoted to the Old Gods." },
    SCARLETCRUSADE = { word="SCARLET CRUSADE", hint="Fanatical order dedicated to destroying undead." },
    DRAGONASPECTS = { word="DRAGON ASPECTS", hint="Titan-empowered guardians of Azeroth." },
    SHATTEREDSUN = { word="SHATTERED SUN OFFENSIVE", hint="Alliance against Kil'jaeden's forces on Quel'Danas." },
    BLACKDRAGONFLIGHT = { word="BLACK DRAGONFLIGHT", hint="Dragonflight once led by Neltharion." },
    EXPLORERSLEAGUE = { word="EXPLORERS' LEAGUE", hint="Dwarven society of history and archaeology." },

    MURLOC = { word="MURLOC", hint="Amphibious coastal dweller with a famous cry." },
    KOBOLD = { word="KOBOLD", hint="Cave dweller fiercely protective of candles." },
    GNOLL = { word="GNOLL", hint="Hyena-like humanoid that travels in packs." },
    HARPY = { word="HARPY", hint="Winged raider from the mountains of Kalimdor." },
    QUILBOAR = { word="QUILBOAR", hint="Bristled people of the Barrens." },
    OGRE = { word="OGRE", hint="Large humanoid with ancient roots on Draenor." },
    DRAGON = { word="DRAGON", hint="Powerful member of one of the dragonflights." },
    BASILISK = { word="BASILISK", hint="Reptile whose gaze can petrify prey." },
    NERUBIAN = { word="NERUBIAN", hint="Spider-like people from beneath Azeroth." },
    MAGNATAUR = { word="MAGNATAUR", hint="Gigantic relative of centaurs from Northrend." },
    GRONN = { word="GRONN", hint="Giant ruler of the ogres of Draenor." },
    NAGA = { word="NAGA", hint="Sea-transformed descendants of the Highborne." },
    TOLVIR = { word="TOL'VIR", hint="Feline titan-forged beings from Uldum." },
    ELEMENTAL = { word="ELEMENTAL", hint="Embodiment of fire, water, earth, or air." },
    DREADLORD = { word="DREADLORD", hint="Manipulative nathrezim from the Shadowlands." },

    MINING = { word="MINING", hint="Gathers ore and stone from mineral veins." },
    HERBALISM = { word="HERBALISM", hint="Gathers plants used in potions and crafting." },
    SKINNING = { word="SKINNING", hint="Collects leather from slain beasts." },
    COOKING = { word="COOKING", hint="Prepares meals that grant useful benefits." },
    FISHING = { word="FISHING", hint="Catches fish in the waters of Azeroth." },
    ALCHEMY = { word="ALCHEMY", hint="Brews potions, elixirs, and transmutes." },
    BLACKSMITHING = { word="BLACKSMITHING", hint="Forges metal weapons and heavy armor." },
    ENCHANTING = { word="ENCHANTING", hint="Enhances equipment with magical effects." },
    ENGINEERING = { word="ENGINEERING", hint="Builds devices, explosives, and mechanical helpers." },
    INSCRIPTION = { word="INSCRIPTION", hint="Creates glyphs, contracts, and magical writings." },
    LEATHERWORKING = { word="LEATHERWORKING", hint="Crafts leather and mail armor." },
    TAILORING = { word="TAILORING", hint="Turns cloth into garments and bags." },
    JEWELCRAFTING = { word="JEWELCRAFTING", hint="Cuts gems and crafts jewelry." },
    ARCHAEOLOGY = { word="ARCHAEOLOGY", hint="Studies fragments of ancient cultures." },
    FIRSTAID = { word="FIRST AID", hint="Former secondary profession for making bandages." },
})

W:Validate()
